# 世界皮肤包名称数据文件。
# 这是“受限 Python 数据文件”，不是可执行插件：加载器只会读取 NAMES 这个字面量字典。
# 左侧键名是系统稳定 ID，不要改；右侧中文字符串才是皮肤包展示名。
# 本包按正式世界风格维护，尽量取原设定体系；只有粒度无法对齐时才用少量原创名缝合。
# 只允许写字典、列表、字符串、数字这类字面量；不要添加 import、函数调用、变量拼接或运行时代码。

NAMES = {
    "places": {
        "cities": {
            "city_tianshu": {
                "name": "友枝町",
                "terrain": "海边小城",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_tianshu_01": "友枝校徽", "trade_city_tianshu_02": "星星发夹", "trade_city_tianshu_03": "小樱便当券"},
                "weapons": {
                    "liuguang_xijian": {"name": "风牌封印杖", "innate_skill": {"skill_id": "liuguang", "name": "风牌召唤"}},
                    "qiankun_pan": {"name": "翔牌封印杖", "innate_skill": {"skill_id": "qiankun", "name": "翔牌召唤"}},
                    "tianji_yuling": {"name": "影牌封印杖", "innate_skill": {"skill_id": "tianji", "name": "影牌召唤"}},
                    "xingheng_fuchen": {"name": "水牌封印杖", "innate_skill": {"skill_id": "xingheng", "name": "水牌召唤"}},
                    "qingxin_ling": {"name": "雨牌封印杖", "innate_skill": {"skill_id": "qingxin", "name": "雨牌召唤"}},
                    "yujing_fujian": {"name": "树牌封印杖", "innate_skill": {"skill_id": "yujing", "name": "树牌召唤"}},
                    "tianxiang_ling": {"name": "跳牌封印杖", "innate_skill": {"skill_id": "tianxiang", "name": "跳牌召唤"}},
                },
            },
            "city_qinglan": {
                "name": "月峰神社",
                "terrain": "神社山坡",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_qinglan_01": "月峰御守", "trade_city_qinglan_02": "雪兔点心盒", "trade_city_qinglan_03": "神社绘马"},
                "weapons": {
                    "qinglan_duanjian": {"name": "幻牌封印杖", "innate_skill": {"skill_id": "fengren", "name": "幻牌召唤"}},
                    "wuxiang_zhujian": {"name": "静牌封印杖", "innate_skill": {"skill_id": "wuxiang", "name": "静牌召唤"}},
                    "lanzhao_feiren": {"name": "雷牌封印杖", "innate_skill": {"skill_id": "lanzhao", "name": "雷牌召唤"}},
                    "qingzhu_dunren": {"name": "剑牌封印杖", "innate_skill": {"skill_id": "qingzhu_dun", "name": "剑牌召唤"}},
                    "qingteng_bi": {"name": "花牌封印杖", "innate_skill": {"skill_id": "qingteng", "name": "花牌召唤"}},
                    "youhuang_ling": {"name": "盾牌封印杖", "innate_skill": {"skill_id": "youhuang", "name": "盾牌召唤"}},
                    "mozhu_jian": {"name": "时牌封印杖", "innate_skill": {"skill_id": "mozhu", "name": "时牌召唤"}},
                },
            },
            "city_chixia": {
                "name": "企鹅公园",
                "terrain": "公园广场",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_chixia_01": "企鹅纪念章", "trade_city_chixia_02": "溜冰票根", "trade_city_chixia_03": "公园气球"},
                "weapons": {
                    "chixia_duandao": {"name": "力牌封印杖", "innate_skill": {"skill_id": "chixia", "name": "力牌召唤"}},
                    "chaohuo_qiang": {"name": "雾牌封印杖", "innate_skill": {"skill_id": "chaohuo", "name": "雾牌召唤"}},
                    "yanbei_nu": {"name": "岚牌封印杖", "innate_skill": {"skill_id": "yanbei", "name": "岚牌召唤"}},
                    "yandu_wandao": {"name": "浮牌封印杖", "innate_skill": {"skill_id": "yandu", "name": "浮牌召唤"}},
                    "dansha_feiren": {"name": "消牌封印杖", "innate_skill": {"skill_id": "dansha", "name": "消牌召唤"}},
                    "zhuyan_dao": {"name": "灯牌封印杖", "innate_skill": {"skill_id": "zhuyan", "name": "灯牌召唤"}},
                    "chilian_wandao": {"name": "移牌封印杖", "innate_skill": {"skill_id": "chilian", "name": "移牌召唤"}},
                },
            },
            "city_xuantie": {
                "name": "钟楼街",
                "terrain": "钟楼街区",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_xuantie_01": "钟楼齿轮", "trade_city_xuantie_02": "旧时钟钥", "trade_city_xuantie_03": "时牌钟坠"},
                "weapons": {
                    "xuantie_zhongji": {"name": "斗牌封印杖", "innate_skill": {"skill_id": "bengshan", "name": "斗牌召唤"}},
                    "zhenyue_fu": {"name": "轮牌封印杖", "innate_skill": {"skill_id": "zhenyue", "name": "轮牌召唤"}},
                    "heiyao_dunren": {"name": "眠牌封印杖", "innate_skill": {"skill_id": "heiyao", "name": "眠牌召唤"}},
                    "fanyue_pan": {"name": "歌牌封印杖", "innate_skill": {"skill_id": "fanyue", "name": "歌牌召唤"}},
                    "luxin_fu": {"name": "小牌封印杖", "innate_skill": {"skill_id": "luxin", "name": "小牌召唤"}},
                    "lingjiao_ji": {"name": "镜牌封印杖", "innate_skill": {"skill_id": "lingjiao", "name": "镜牌召唤"}},
                    "guming_dunren": {"name": "迷牌封印杖", "innate_skill": {"skill_id": "guming", "name": "迷牌召唤"}},
                },
            },
            "city_wanyao": {
                "name": "木之本家",
                "terrain": "住宅街",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_wanyao_01": "星杖挂坠", "trade_city_wanyao_02": "库洛书签", "trade_city_wanyao_03": "小可布丁券"},
                "weapons": {
                    "wanyao_tengzhang": {"name": "返牌封印杖", "innate_skill": {"skill_id": "huichun", "name": "返牌召唤"}},
                    "lingfeng_bi": {"name": "击牌封印杖", "innate_skill": {"skill_id": "lingfeng", "name": "击牌召唤"}},
                    "yaowang_fuchen": {"name": "甜牌封印杖", "innate_skill": {"skill_id": "yaowang", "name": "甜牌召唤"}},
                    "fengwang_ling": {"name": "驱牌封印杖", "innate_skill": {"skill_id": "fengwang", "name": "驱牌召唤"}},
                    "lingmu_zhang": {"name": "大牌封印杖", "innate_skill": {"skill_id": "lingmu", "name": "大牌召唤"}},
                    "luming_qiang": {"name": "创牌封印杖", "innate_skill": {"skill_id": "luming", "name": "创牌召唤"}},
                    "zhupo_zhang": {"name": "替牌封印杖", "innate_skill": {"skill_id": "zhupo", "name": "替牌召唤"}},
                },
            },
            "city_yunmeng": {
                "name": "大道寺宅",
                "terrain": "洋馆庭院",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_yunmeng_01": "知世缎带", "trade_city_yunmeng_02": "摄影胶卷", "trade_city_yunmeng_03": "天使蕾丝"},
                "weapons": {
                    "duannian_zhang": {"name": "冻牌封印杖", "innate_skill": {"skill_id": "duannian", "name": "冻牌召唤"}},
                    "mengwu_ling": {"name": "火牌封印杖", "innate_skill": {"skill_id": "mengwu", "name": "火牌召唤"}},
                    "shuijing_jian": {"name": "矢牌封印杖", "innate_skill": {"skill_id": "shuijing", "name": "矢牌召唤"}},
                    "nimeng_deng": {"name": "泡牌封印杖", "innate_skill": {"skill_id": "nimeng", "name": "泡牌召唤"}},
                    "jinghu_xijian": {"name": "波牌封印杖", "innate_skill": {"skill_id": "jinghu", "name": "波牌召唤"}},
                    "heishui_bi": {"name": "云牌封印杖", "innate_skill": {"skill_id": "heishui", "name": "云牌召唤"}},
                    "duhun_deng": {"name": "声牌封印杖", "innate_skill": {"skill_id": "duhun", "name": "声牌召唤"}},
                },
            },
            "city_liusha": {
                "name": "友枝小学",
                "terrain": "校园",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_liusha_01": "友枝课本", "trade_city_liusha_02": "制服纽扣", "trade_city_liusha_03": "体育哨"},
                "weapons": {
                    "liusha_feiren": {"name": "砂牌封印杖", "innate_skill": {"skill_id": "shaying", "name": "砂牌召唤"}},
                    "jueying_feijian": {"name": "双牌封印杖", "innate_skill": {"skill_id": "jueying", "name": "双牌召唤"}},
                    "duyun_wandao": {"name": "地牌封印杖", "innate_skill": {"skill_id": "duyun", "name": "地牌召唤"}},
                    "shajin_dao": {"name": "秤牌封印杖", "innate_skill": {"skill_id": "shajin", "name": "秤牌召唤"}},
                    "yingye_feiren": {"name": "锁牌封印杖", "innate_skill": {"skill_id": "yingye", "name": "锁牌召唤"}},
                    "langhao_feiren": {"name": "穿牌封印杖", "innate_skill": {"skill_id": "langhao", "name": "穿牌召唤"}},
                },
            },
            "city_hanshuang": {
                "name": "友枝中学",
                "terrain": "校园",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_hanshuang_01": "星条领结", "trade_city_hanshuang_02": "社团徽章", "trade_city_hanshuang_03": "弓道护符"},
                "weapons": {
                    "xuehe_bi": {"name": "光牌封印杖", "innate_skill": {"skill_id": "xueying", "name": "光牌召唤"}},
                    "zhenhun_ling": {"name": "暗牌封印杖", "innate_skill": {"skill_id": "liehun", "name": "暗牌召唤"}},
                    "yueshi_wandao": {"name": "无牌封印杖", "innate_skill": {"skill_id": "yueshi", "name": "无牌召唤"}},
                    "hanyan_fuchen": {"name": "希望牌封印杖", "innate_skill": {"skill_id": "hanyan", "name": "希望牌召唤"}},
                    "yuehen_bi": {"name": "疾风牌封印杖", "innate_skill": {"skill_id": "yuehen", "name": "疾风牌召唤"}},
                    "chenyuan_dao": {"name": "包围牌封印杖", "innate_skill": {"skill_id": "chenyuan", "name": "包围牌召唤"}},
                },
            },
            "city_leize": {
                "name": "库洛书库",
                "terrain": "魔法书库",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_leize_01": "库洛封皮", "trade_city_leize_02": "魔法阵拓片", "trade_city_leize_03": "月铃残音"},
                "weapons": {
                    "pojun_qiang": {"name": "水源牌封印杖", "innate_skill": {"skill_id": "pojun", "name": "水源牌召唤"}},
                    "leiguang_duanren": {"name": "反射牌封印杖", "innate_skill": {"skill_id": "leiguang", "name": "反射牌召唤"}},
                    "zidian_fu": {"name": "行动牌封印杖", "innate_skill": {"skill_id": "zidian", "name": "行动牌召唤"}},
                    "leihou_dunren": {"name": "引力牌封印杖", "innate_skill": {"skill_id": "leihou", "name": "引力牌召唤"}},
                    "guigen_dunren": {"name": "记录牌封印杖", "innate_skill": {"skill_id": "guigen", "name": "记录牌召唤"}},
                    "shouhun_ling": {"name": "飞翔牌封印杖", "innate_skill": {"skill_id": "shouhun", "name": "飞翔牌召唤"}},
                },
            },
            "city_bichao": {
                "name": "友枝水族馆",
                "terrain": "水族馆",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_bichao_01": "水族馆贝票", "trade_city_bichao_02": "水牌玻璃珠", "trade_city_bichao_03": "蓝鲸玩偶"},
                "weapons": {
                    "xuangui_dunren": {"name": "透明牌封印杖", "innate_skill": {"skill_id": "xuandun", "name": "透明牌召唤"}},
                    "duanhai_jian": {"name": "螺旋牌封印杖", "innate_skill": {"skill_id": "duanhai", "name": "螺旋牌召唤"}},
                    "chaoxi_fuchen": {"name": "午睡牌封印杖", "innate_skill": {"skill_id": "chaoxi", "name": "午睡牌召唤"}},
                    "cangming_ji": {"name": "镜像牌封印杖", "innate_skill": {"skill_id": "cangming", "name": "镜像牌召唤"}},
                    "yingyue_pan": {"name": "逆转牌封印杖", "innate_skill": {"skill_id": "yingyue", "name": "逆转牌召唤"}},
                    "wumu_dunren": {"name": "摇摆牌封印杖", "innate_skill": {"skill_id": "wumu", "name": "摇摆牌召唤"}},
                },
            },
            "city_xingyun": {
                "name": "钟国迷宫",
                "terrain": "迷宫异界",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_xingyun_01": "钟国茶匙", "trade_city_xingyun_02": "梦境怀表", "trade_city_xingyun_03": "爱丽丝书页"},
                "weapons": {
                    "zhuixing_nu": {"name": "火焰牌封印杖", "innate_skill": {"skill_id": "zhuixing", "name": "火焰牌召唤"}},
                    "chuanyun_lingqiang": {"name": "冰雹牌封印杖", "innate_skill": {"skill_id": "chuanyun", "name": "冰雹牌召唤"}},
                    "xingluo_fachen": {"name": "梦之钥封印杖", "innate_skill": {"skill_id": "xingluo", "name": "梦之钥召唤"}},
                    "yunxing_pan": {"name": "星之钥封印杖", "innate_skill": {"skill_id": "yunxing", "name": "星之钥召唤"}},
                    "jinlu_pan": {"name": "封印钥封印杖", "innate_skill": {"skill_id": "jinlu", "name": "封印钥召唤"}},
                    "zhuxie_qiang": {"name": "库洛书封印杖", "innate_skill": {"skill_id": "zhuxie", "name": "库洛书召唤"}},
                },
            },
        },
        "realm": {"realm_taixu": {"name": "透明牌梦境", "terrain": "梦境秘域", "roles": ["secret_realm", "dynamic_battle"]}},
        "buyers": {
            "buyer_zhenyaosi": {"name": "封印审判庭", "terrain": "审判庭", "roles": ["special_buyer", "war_prep"]},
            "buyer_fumodian": {"name": "月之审判台", "terrain": "月光高台", "roles": ["special_buyer", "war_prep"]},
            "buyer_guishi": {"name": "镜牌旧市", "terrain": "镜中旧市", "roles": ["special_buyer", "war_prep"]},
            "buyer_longyuan": {"name": "库洛魔法阵", "terrain": "魔法阵", "roles": ["special_buyer", "war_prep"]},
            "buyer_wanshou": {"name": "守护兽议会", "terrain": "守护兽会所", "roles": ["special_buyer", "war_prep"]},
            "buyer_pojun": {"name": "时间钟塔", "terrain": "钟塔", "roles": ["special_buyer", "war_prep"]},
        },
        "recycles": {
            "recycle_weapon": {"name": "星杖工坊", "terrain": "魔杖工坊", "roles": ["recycle"]},
            "recycle_gem": {"name": "宝石缎带屋", "terrain": "缎带小屋", "roles": ["recycle"]},
            "recycle_book": {"name": "库洛书房", "terrain": "魔法书房", "roles": ["recycle"]},
        },
    },
    "world_items": {
        "medicine": {
            "material": {
                "world_med_xueqidan_1": "花牌花蜜",
                "world_med_xueqidan_2": "树牌嫩芽",
                "world_med_yinmingcao_1": "水牌露珠",
                "world_med_yinmingcao_2": "雨牌清滴",
                "world_med_huichunlu_1": "甜牌糖霜",
                "world_med_huichunlu_2": "歌牌薄荷",
                "world_med_ningshenlu_1": "光牌星砂",
                "world_med_ningshenlu_2": "希望牌花瓣",
            },
            "catalyst": {
                "world_med_shenggudan_1": "镜牌银粉",
                "world_med_shenggudan_2": "时牌钟砂",
                "world_med_yanghundan_1": "盾牌金箔",
                "world_med_yanghundan_2": "库洛封蜡",
            },
            "fuel": {
                "world_med_xueqidan_3": "火牌余烬",
                "world_med_yinmingcao_3": "雷牌电屑",
                "world_med_huichunlu_3": "灯牌萤光",
                "world_med_ningshenlu_3": "星杖木屑",
                "world_med_shenggudan_3": "月铃冷辉",
                "world_med_yanghundan_3": "小可布丁糖",
            },
        },
        "life": {
            "chengshi": {
                "world_life_chengshi_1": "友枝米团",
                "world_life_chengshi_2": "月峰麦饼",
                "world_life_chengshi_3": "小樱煎蛋卷",
                "world_life_chengshi_4": "知世曲奇",
                "world_life_chengshi_5": "雪兔饭团",
            },
            "yanxian": {
                "world_life_yanxian_1": "企鹅公园盐汽水",
                "world_life_yanxian_2": "水族馆海盐",
                "world_life_yanxian_3": "友枝海苔",
                "world_life_yanxian_4": "小可薯片",
                "world_life_yanxian_5": "桃矢便当肉脯",
            },
            "shuijing": {
                "world_life_shuijing_1": "水牌净瓶",
                "world_life_shuijing_2": "雨牌滤纸",
                "world_life_shuijing_3": "月峰清泉签",
                "world_life_shuijing_4": "泡牌洗瓶",
                "world_life_shuijing_5": "透明玻璃杯",
            },
            "yibei": {
                "world_life_yibei_1": "知世缎带布",
                "world_life_yibei_2": "小樱校服布",
                "world_life_yibei_3": "星星发饰绒",
                "world_life_yibei_4": "库洛披肩料",
                "world_life_yibei_5": "月铃白纱",
            },
            "ranan": {
                "world_life_ranan_1": "灯牌夜烛",
                "world_life_ranan_2": "光牌暖芯",
                "world_life_ranan_3": "火牌小炉",
                "world_life_ranan_4": "守护兽铃香",
                "world_life_ranan_5": "月牌安眠香",
            },
        },
        "build": {
            "jichu": {
                "world_build_jichu_1": "友枝白砖",
                "world_build_jichu_2": "月峰木梁",
                "world_build_jichu_3": "企鹅广场石",
                "world_build_jichu_4": "钟楼铜轴",
                "world_build_jichu_5": "库洛封皮板",
            },
            "chengfang": {
                "world_build_chengfang_1": "盾牌护栏",
                "world_build_chengfang_2": "锁牌门栓",
                "world_build_chengfang_3": "镜牌警铃",
                "world_build_chengfang_4": "影牌帷幕",
                "world_build_chengfang_5": "月之结界柱",
            },
            "shuihuo": {
                "world_build_shuihuo_1": "水牌导管",
                "world_build_shuihuo_2": "泡牌净槽",
                "world_build_shuihuo_3": "火牌炉芯",
                "world_build_shuihuo_4": "雷牌避针",
                "world_build_shuihuo_5": "雨牌蓄水盘",
            },
            "zhenji": {
                "world_build_zhenji_1": "库洛魔法阵粉",
                "world_build_zhenji_2": "星杖阵钉",
                "world_build_zhenji_3": "月铃界石",
                "world_build_zhenji_4": "封印符纸",
                "world_build_zhenji_5": "透明牌阵基",
            },
            "huashi": {
                "world_build_huashi_1": "知世花边檐",
                "world_build_huashi_2": "星星窗格",
                "world_build_huashi_3": "小樱羽饰灯",
                "world_build_huashi_4": "库洛月纹壁",
                "world_build_huashi_5": "梦之钥门牌",
            },
        },
        "relic": {
            "weiyun": {
                "world_relic_weiyun_1": "库洛残页",
                "world_relic_weiyun_2": "封印钥坠",
                "world_relic_weiyun_3": "星杖碎星",
                "world_relic_weiyun_4": "月铃回声",
                "world_relic_weiyun_5": "小可羽毛",
                "world_relic_weiyun_6": "镜牌碎面",
                "world_relic_weiyun_7": "友枝旧照",
                "world_relic_weiyun_8": "企鹅雕章",
            },
            "zhongyun": {
                "world_relic_zhongyun_1": "库洛罗盘",
                "world_relic_zhongyun_2": "星之钥影",
                "world_relic_zhongyun_3": "梦之钥影",
                "world_relic_zhongyun_4": "无牌空匣",
                "world_relic_zhongyun_5": "希望牌花冠",
                "world_relic_zhongyun_6": "月之审判羽",
                "world_relic_zhongyun_7": "太阳守护纹",
                "world_relic_zhongyun_8": "钟国怀表",
            },
            "houyun": {
                "world_relic_houyun_1": "库洛书原页",
                "world_relic_houyun_2": "星杖原核",
                "world_relic_houyun_3": "梦杖原核",
                "world_relic_houyun_4": "光暗双牌匣",
                "world_relic_houyun_5": "透明牌空座",
                "world_relic_houyun_6": "爱丽丝钟冠",
                "world_relic_houyun_7": "守护者契印",
                "world_relic_houyun_8": "封印之门钥",
            },
        },
        "loot": {
            "yao": {
                "loot_yao_1": "失控风牌羽",
                "loot_yao_2": "失控跳牌耳",
                "loot_yao_3": "失控树牌藤",
                "loot_yao_4": "失控花牌冠",
                "loot_yao_5": "失控云牌絮",
                "loot_yao_6": "失控双牌影",
            },
            "mo": {
                "loot_mo_1": "无牌空屑",
                "loot_mo_2": "暗牌黑羽",
                "loot_mo_3": "雾牌蚀珠",
                "loot_mo_4": "影牌墨痕",
                "loot_mo_5": "雷牌焦角",
                "loot_mo_6": "火牌灼灰",
            },
            "gui": {
                "loot_gui_1": "梦牌残梦",
                "loot_gui_2": "眠牌睡雾",
                "loot_gui_3": "幻牌面纱",
                "loot_gui_4": "静牌封音",
                "loot_gui_5": "消牌白痕",
                "loot_gui_6": "返牌旧影",
            },
            "long": {"loot_long_1": "地牌龙鳞", "loot_long_2": "水牌龙沫", "loot_long_3": "火牌龙焰"},
            "shou": {
                "loot_shou_1": "小可金毛",
                "loot_shou_2": "雪兔月羽",
                "loot_shou_3": "斯比兽角",
                "loot_shou_4": "跳牌软爪",
                "loot_shou_5": "力牌腕甲",
                "loot_shou_6": "驱牌蹄铃",
            },
            "bing": {
                "loot_bing_1": "剑牌断锋",
                "loot_bing_2": "矢牌尾羽",
                "loot_bing_3": "击牌裂弹",
                "loot_bing_4": "盾牌碎甲",
                "loot_bing_5": "锁牌断链",
                "loot_bing_6": "时牌钟针",
            },
        },
    },
    "ring": {
        "recovery": {
            "fudai": "星之福袋",
            "xueqidan": "花牌蜜糖",
            "yinmingcao": "树牌药露",
            "huichunlu": "水牌清露",
            "ningshenlu": "眠牌薄荷糖",
            "shenggudan": "盾牌修补糖",
            "yanghundan": "歌牌安魂糖",
        },
        "gems": {
            "huxinyu": "护牌心玉",
            "xuangui shi": "地牌玄龟石",
            "shanbi fozhu": "翔牌佛珠",
            "mingxin fozhu": "镜牌明心珠",
            "huichun feicui": "花牌翡翠",
            "qingxin manao": "水牌玛瑙",
            "qingshen shuijing": "风牌水晶",
            "jucai zijing": "甜牌紫晶",
            "kangbao fuwen": "盾牌符文",
        },
        "special": {"kaikongqi": "封印开孔钥", "xisuiye": "星光洗髓露", "cuifengdan": "星杖淬锋砂", "liuguang_qian": "星光签"},
    },
    "weapons": {
        "skill_books": {
            "fengren_shu": "风牌手札",
            "extreme_fengren_shu": "极·风牌手札",
            "shaying_shu": "翔牌手札",
            "extreme_shaying_shu": "极·翔牌手札",
            "liuguang_shu": "影牌手札",
            "extreme_liuguang_shu": "极·影牌手札",
            "zhuixing_shu": "水牌手札",
            "extreme_zhuixing_shu": "极·水牌手札",
            "poxie_shu": "雨牌手札",
            "extreme_poxie_shu": "极·雨牌手札",
            "bengshan_shu": "树牌手札",
            "extreme_bengshan_shu": "极·树牌手札",
            "chuanyun_shu": "跳牌手札",
            "extreme_chuanyun_shu": "极·跳牌手札",
            "zhenyue_shu": "幻牌手札",
            "extreme_zhenyue_shu": "极·幻牌手札",
            "zhuoxin_shu": "静牌手札",
            "extreme_zhuoxin_shu": "极·静牌手札",
            "xueyu_shu": "雷牌手札",
            "extreme_xueyu_shu": "极·雷牌手札",
            "duyun_shu": "剑牌手札",
            "extreme_duyun_shu": "极·剑牌手札",
            "canyan_shu": "花牌手札",
            "extreme_canyan_shu": "极·花牌手札",
            "duannian_shu": "盾牌手札",
            "extreme_duannian_shu": "极·盾牌手札",
            "zhenhun_shu": "时牌手札",
            "extreme_zhenhun_shu": "极·时牌手札",
            "tianji_shu": "力牌手札",
            "extreme_tianji_shu": "极·力牌手札",
            "mengwu_shu": "雾牌手札",
            "extreme_mengwu_shu": "极·雾牌手札",
            "huichun_shu": "岚牌手札",
            "extreme_huichun_shu": "极·岚牌手札",
            "xuandun_shu": "浮牌手札",
            "extreme_xuandun_shu": "极·浮牌手札",
            "xueqi_shu": "消牌手札",
            "extreme_xueqi_shu": "极·消牌手札",
            "lingmu_shu": "灯牌手札",
            "extreme_lingmu_shu": "极·灯牌手札",
            "fanzhen_shu": "移牌手札",
            "extreme_fanzhen_shu": "极·移牌手札",
            "guiren_shu": "斗牌手札",
            "extreme_guiren_shu": "极·斗牌手札",
            "jieshi_shu": "轮牌手札",
            "extreme_jieshi_shu": "极·轮牌手札",
            "xuanyao_shu": "眠牌手札",
            "extreme_xuanyao_shu": "极·眠牌手札",
            "wuxiang_shu": "歌牌手札",
            "extreme_wuxiang_shu": "极·歌牌手札",
            "duanhai_shu": "小牌手札",
            "extreme_duanhai_shu": "极·小牌手札",
            "jueying_shu": "镜牌手札",
            "extreme_jueying_shu": "极·镜牌手札",
            "pojun_shu": "迷牌手札",
            "extreme_pojun_shu": "极·迷牌手札",
            "xingluo_shu": "返牌手札",
            "extreme_xingluo_shu": "极·返牌手札",
            "qiankun_shu": "击牌手札",
            "extreme_qiankun_shu": "极·击牌手札",
            "pozhen_shu": "甜牌手札",
            "extreme_pozhen_shu": "极·甜牌手札",
            "yujing_shu": "驱牌手札",
            "extreme_yujing_shu": "极·驱牌手札",
            "yueshi_shu": "大牌手札",
            "extreme_yueshi_shu": "极·大牌手札",
            "jinghu_shu": "创牌手札",
            "extreme_jinghu_shu": "极·创牌手札",
            "yingye_shu": "替牌手札",
            "extreme_yingye_shu": "极·替牌手札",
            "qingxin_shu": "冻牌手札",
            "extreme_qingxin_shu": "极·冻牌手札",
        },
        "types": {
            "axe": "星斧",
            "balanced": "星衡",
            "bell": "月铃",
            "blade": "飞牌刃",
            "crossbow": "矢牌弩",
            "dagger": "影牌匕",
            "disc": "时牌盘",
            "halberd": "剑牌戟",
            "saber": "火牌刀",
            "shield_blade": "盾牌刃",
            "spear": "翔牌枪",
            "staff": "封印杖",
            "sword": "剑牌",
            "whisk": "风牌拂尘",
        },
    },
    "actors": {
        "monsters": {
            "qinglang": "失控风牌",
            "huyao": "影牌幻影",
            "shanzhu": "跳牌兽",
            "baigui": "白骨库洛影",
            "shayan": "砂牌漩涡",
            "mopi_jiang": "暗牌魔影",
            "xuanling": "钟楼傀儡",
            "guijiang": "鬼火牌灵",
            "hanpo": "冻牌寒魂",
            "tiejia_bing": "铠甲旧兵",
            "leishou": "雷牌兽",
            "yaotong_niao": "迷牌乌鸦",
            "jiaolong": "水牌龙影",
            "longxu_ying": "地牌龙须",
            "mohun": "无牌魔魂",
            "moyan_shi": "火牌魔使",
            "pojun": "剑牌残将",
            "duanren_jiang": "断刃库洛兵",
        },
        "physiques": {
            "fanti": {
                "name": "普通收牌体",
                "grade": "初牌",
                "kind": "无牌",
                "desc": "普通收牌体受无牌引导，魔力表现对应原体质：平平无奇，却也最稳，所有玩家默认从这里开始。",
            },
            "qingfeng_lingti": {
                "name": "风牌亲和",
                "grade": "库洛牌",
                "kind": "风牌",
                "desc": "风牌亲和受风牌引导，魔力表现对应原体质：气息轻灵，稍微更容易避开伤害。",
            },
            "houde_lingti": {
                "name": "地牌亲和",
                "grade": "库洛牌",
                "kind": "力牌",
                "desc": "地牌亲和受力牌引导，魔力表现对应原体质：根基厚实，早期防御更稳。",
            },
            "lingquan_ti": {
                "name": "水牌亲和",
                "grade": "库洛牌",
                "kind": "水牌",
                "desc": "水牌亲和受水牌引导，魔力表现对应原体质：体内如有活泉，休息恢复更好。",
            },
            "tiegu_ti": {
                "name": "盾牌亲和",
                "grade": "库洛牌",
                "kind": "盾牌",
                "desc": "盾牌亲和受盾牌引导，魔力表现对应原体质：骨骼坚韧，承伤更稳。",
            },
            "mingxin_ti": {
                "name": "镜牌亲和",
                "grade": "库洛牌",
                "kind": "镜牌",
                "desc": "镜牌亲和受镜牌引导，魔力表现对应原体质：心神清明，精神上限略高。",
            },
            "qianye_lingti": {
                "name": "树牌亲和",
                "grade": "库洛牌",
                "kind": "树牌",
                "desc": "树牌亲和受树牌引导，魔力表现对应原体质：生机细密，血气和恢复都有一点优势。",
            },
            "qingmu_xuanti": {
                "name": "花牌灵体",
                "grade": "小樱牌",
                "kind": "树牌",
                "desc": "花牌灵体受树牌引导，魔力表现对应原体质：偏生机恢复，跑商手续费略吃亏。",
            },
            "xuanbing_linggu": {
                "name": "冻牌灵骨",
                "grade": "小樱牌",
                "kind": "雪牌",
                "desc": "冻牌灵骨受雪牌引导，魔力表现对应原体质：防御冷硬，恢复稍慢。",
            },
            "chixia_lingti": {
                "name": "火牌灵体",
                "grade": "小樱牌",
                "kind": "火牌",
                "desc": "火牌灵体受火牌引导，魔力表现对应原体质：血气旺盛，精神上限略低。",
            },
            "leiwenzhanti": {
                "name": "雷牌战体",
                "grade": "小樱牌",
                "kind": "雷牌",
                "desc": "雷牌战体受雷牌引导，魔力表现对应原体质：身法迅疾，生活经营不太细致。",
            },
            "yuyue_ti": {
                "name": "月牌玉体",
                "grade": "小樱牌",
                "kind": "月牌",
                "desc": "月牌玉体受月牌引导，魔力表现对应原体质：精神与恢复突出，血气略薄。",
            },
            "jianxin_xuangu": {
                "name": "剑牌玄骨",
                "grade": "小樱牌",
                "kind": "剑牌",
                "desc": "剑牌玄骨受剑牌引导，魔力表现对应原体质：适合冒险寻机，身板略薄。",
            },
            "longxiang_baoti": {
                "name": "力牌宝体",
                "grade": "星杖牌",
                "kind": "力牌",
                "desc": "力牌宝体受力牌引导，魔力表现对应原体质：血厚防稳，跑商不灵活。",
            },
            "xinghe_lingti": {
                "name": "星牌灵体",
                "grade": "星杖牌",
                "kind": "星牌",
                "desc": "星牌灵体受星牌引导，魔力表现对应原体质：擅长探险寻宝，防御略低。",
            },
            "taiyin_yuti": {
                "name": "眠牌玉体",
                "grade": "星杖牌",
                "kind": "月牌",
                "desc": "眠牌玉体受月牌引导，魔力表现对应原体质：恢复和精神很强，血气偏薄。",
            },
            "taiyang_yanti": {
                "name": "光牌炎体",
                "grade": "星杖牌",
                "kind": "火牌",
                "desc": "光牌炎体受火牌引导，魔力表现对应原体质：血气极盛，恢复和跑商略差。",
            },
            "canghai_daoti": {
                "name": "水牌道体",
                "grade": "星杖牌",
                "kind": "波牌",
                "desc": "水牌道体受波牌引导，魔力表现对应原体质：精神绵长、恢复平顺，防御偏弱。",
            },
            "wuyue_baoti": {
                "name": "地牌宝体",
                "grade": "星杖牌",
                "kind": "地牌",
                "desc": "地牌宝体受地牌引导，魔力表现对应原体质：防御厚重，精神和探险灵活性较差。",
            },
            "hunyuan_daoti": {
                "name": "库洛镇岳体",
                "grade": "透明牌",
                "kind": "地牌",
                "desc": "库洛镇岳体受地牌引导，魔力表现对应原体质：极端守御体质，精神与跑商是短板。",
            },
            "wugou_xianji": {
                "name": "希望无垢体",
                "grade": "透明牌",
                "kind": "净化牌",
                "desc": "希望无垢体受净化牌引导，魔力表现对应原体质：恢复与精神突出，正面承伤略弱。",
            },
            "wanxiang_lingtai": {
                "name": "幻牌游身体",
                "grade": "透明牌",
                "kind": "风牌",
                "desc": "幻牌游身体受风牌引导，魔力表现对应原体质：闪避和探险极强，血防明显偏薄。",
            },
            "zifu_tianti": {
                "name": "月之神体",
                "grade": "透明牌",
                "kind": "镜牌",
                "desc": "月之神体受镜牌引导，魔力表现对应原体质：精神海宽广，血气不是优势。",
            },
            "qianqiu_jianmai": {
                "name": "剑牌灵脉",
                "grade": "透明牌",
                "kind": "剑牌",
                "desc": "剑牌灵脉受剑牌引导，魔力表现对应原体质：适合险地寻剑，恢复不算出色。",
            },
            "shenxiao_leiti": {
                "name": "雷牌神霄体",
                "grade": "透明牌",
                "kind": "雷牌",
                "desc": "雷牌神霄体受雷牌引导，魔力表现对应原体质：迅烈难伤，恢复和跑商都粗糙。",
            },
            "xiantian_daotai": {
                "name": "花牌药胎",
                "grade": "守护者",
                "kind": "水牌",
                "desc": "花牌药胎受水牌引导，魔力表现对应原体质：恢复近乎夸张，但肉身承压偏弱。",
            },
            "canglong_shengti": {
                "name": "翔牌圣体",
                "grade": "守护者",
                "kind": "创牌",
                "desc": "翔牌圣体受创牌引导，魔力表现对应原体质：血气如海，精神和经营能力是短板。",
            },
            "jiuyao_shengti": {
                "name": "星河命体",
                "grade": "守护者",
                "kind": "星牌",
                "desc": "星河命体受星牌引导，魔力表现对应原体质：天生会找机会，适合探险和跑商，血防较薄。",
            },
            "bumie_jinshen": {
                "name": "盾牌金身体",
                "grade": "守护者",
                "kind": "盾牌",
                "desc": "盾牌金身体受盾牌引导，魔力表现对应原体质：最硬的防御路线，精神、探险和跑商都笨重。",
            },
            "taixu_xianmai": {
                "name": "透明仙脉",
                "grade": "守护者",
                "kind": "迷牌",
                "desc": "透明仙脉受迷牌引导，魔力表现对应原体质：飘忽难捉，探险极强，但正面血防很低。",
            },
            "hongmeng_xuanti": {
                "name": "梦之钥玄体",
                "grade": "守护者",
                "kind": "迷牌",
                "desc": "梦之钥玄体受迷牌引导，魔力表现对应原体质：精神深不可测，却不适合硬扛和经营。",
            },
        },
        "enemy_kinds": {
            "ancient_guard": "库洛古卫",
            "beast": "牌兽",
            "default": "失控牌灵",
            "demon": "暗牌魔影",
            "demon_general": "魔影将",
            "dragon": "地水龙",
            "dragon_shadow": "地牌龙影",
            "ghost": "梦魂",
            "puppet": "钟楼傀儡",
            "soldier": "剑牌兵",
            "wandering_soul": "游梦魂",
            "yao": "牌妖",
            "yaojun": "牌妖君",
        },
        "enemy_skills": {
            "enemy_skill_yao_bite": "跳牌撕咬",
            "enemy_skill_yaojun_shadow": "影牌裂影",
            "enemy_skill_beast_charge": "力牌冲撞",
            "enemy_skill_dragon_breath": "水牌龙息",
            "enemy_skill_dragon_shadow_breath": "地牌吐息",
            "enemy_skill_ghost_bite": "梦魂噬念",
            "enemy_skill_wandering_soul_bind": "迷牌缠身",
            "enemy_skill_demon_flame": "火牌灼心",
            "enemy_skill_demon_general_break": "暗牌破阵",
            "enemy_skill_soldier_armor_break": "剑牌破甲",
            "enemy_skill_ancient_guard_suppress": "月之镇压",
            "enemy_skill_puppet_crush": "钟楼重压",
            "enemy_skill_default": "库洛一击",
        },
    },
    "wormhole": {
        "bosses": {
            "worm_boss_01": "异界牌灵·疾风界游者",
            "worm_boss_02": "异界牌灵·陨钟泰坦",
            "worm_boss_03": "异界牌灵·赤焰无牌",
            "worm_boss_04": "异界牌灵·缄梦巫王",
            "worm_boss_05": "异界牌灵·苍树不死者",
            "worm_boss_06": "异界牌灵·回盾镜魔",
            "worm_boss_07": "异界牌灵·断星剑王",
            "worm_boss_08": "异界牌灵·星环审判者",
        },
        "flows": {
            "worm_flow_swift": "翔牌连击",
            "worm_flow_heavy": "力牌破防",
            "worm_flow_dot": "火牌灼烧",
            "worm_flow_control": "迷牌压制",
            "worm_flow_survival": "盾牌续航",
            "worm_flow_counter": "镜牌反击",
            "worm_flow_execute": "剑牌斩杀",
            "worm_flow_leader": "守护者协作",
        },
        "war_prep_bosses": {
            "war_boss_zhenyaosi_01": "失控风牌王",
            "war_boss_zhenyaosi_02": "裂影牌后",
            "war_boss_zhenyaosi_03": "万羽云牌主",
            "war_boss_fumodian_01": "黑铠暗牌魔",
            "war_boss_fumodian_02": "焚契火牌侯",
            "war_boss_fumodian_03": "坠岳地牌君",
            "war_boss_guishi_01": "无灯梦牌主",
            "war_boss_guishi_02": "缚魂迷牌巫",
            "war_boss_guishi_03": "纸城幻牌王",
            "war_boss_longyuan_01": "逆鳞水牌君",
            "war_boss_longyuan_02": "潮骸地牌龙",
            "war_boss_longyuan_03": "星渊断角龙",
            "war_boss_wanshou_01": "荒骨力牌兽",
            "war_boss_wanshou_02": "苍鬃跳牌兽",
            "war_boss_wanshou_03": "万蹄驱牌王",
            "war_boss_pojun_01": "星甲剑牌帅",
            "war_boss_pojun_02": "断旗时牌兵主",
            "war_boss_pojun_03": "铁潮库洛军魂",
        },
        "war_prep_affixes": {
            "war_prep_affix_exposed_nest": "残牌已露",
            "war_prep_affix_half_open_gate": "旧门半开",
            "war_prep_affix_war_marks": "审判回涌",
            "war_prep_affix_warm_embers": "余星未冷",
            "war_prep_affix_gathering_enemies": "牌灵聚形",
            "war_prep_affix_unstable_rift": "裂口不稳",
        },
    },
    "secret_realm": {
        "environments": {
            "secret_env_youming_wind": {"name": "风牌乱流", "desc": "阴风压魂，怪物精神压迫更重。"},
            "secret_env_mirror_sky": {"name": "镜牌天幕", "desc": "镜影错乱，遭遇强度起伏更大。"},
            "secret_env_dragon_bone_dust": {"name": "地牌骨尘", "desc": "龙骨尘暴翻涌，怪物血防更厚。"},
            "secret_env_star_fire_rain": {"name": "星火牌雨", "desc": "星火落如雨，怪物攻势更烈。"},
            "secret_env_returning_tide": {"name": "回梦潮", "desc": "归墟潮汐反复，战斗更拖长。"},
        }
    },
    "system": {
        "quality": {"quality_common": "普通牌", "quality_good": "库洛牌", "quality_rare": "小樱牌", "quality_epic": "透明牌"},
        "currency": {"raw_stones": "星砂"},
        "levels": {
            "1": "封印之钥·梦中星光",
            "2": "封印之钥·小可苏醒",
            "3": "封印之钥·咒语成声",
            "4": "封印之钥·星阵初画",
            "5": "封印之钥·牌息可闻",
            "6": "封印之钥·风影初缚",
            "7": "封印之钥·飞翔练习",
            "8": "封印之钥·影子听令",
            "9": "封印之钥·收牌成习",
            "10": "封印之钥·牌书初稳",
            "11": "库洛牌·风水归册",
            "12": "库洛牌·树雨应声",
            "13": "库洛牌·跳幻入页",
            "14": "库洛牌·静雷同调",
            "15": "库洛牌·剑花守心",
            "16": "库洛牌·盾时并用",
            "17": "库洛牌·光暗将醒",
            "18": "库洛牌·库洛气息",
            "19": "库洛牌·最后审判",
            "20": "库洛牌·审判通过",
            "21": "小樱牌·星杖初握",
            "22": "小樱牌·牌名重写",
            "23": "小樱牌·旧契松动",
            "24": "小樱牌·新契成形",
            "25": "小樱牌·风牌转化",
            "26": "小樱牌·水牌转化",
            "27": "小樱牌·光暗转化",
            "28": "小樱牌·时牌转化",
            "29": "小樱牌·星力入册",
            "30": "小樱牌·转化圆满",
            "31": "守护者·小可同行",
            "32": "守护者·月影试炼",
            "33": "守护者·雪兔明心",
            "34": "守护者·日月同契",
            "35": "守护者·牌灵护主",
            "36": "守护者·审判静默",
            "37": "守护者·月铃归心",
            "38": "守护者·星杖回应",
            "39": "守护者·守护成阵",
            "40": "守护者·友枝守夜",
            "41": "星杖·星轨入阵",
            "42": "星杖·多牌同调",
            "43": "星杖·愿力入杖",
            "44": "星杖·魔力稳流",
            "45": "星杖·牌阵连携",
            "46": "星杖·星光成翼",
            "47": "星杖·库洛回响",
            "48": "星杖·星辉护界",
            "49": "星杖·牌书无缺",
            "50": "星杖·梦钥将醒",
            "51": "梦之钥·梦门初开",
            "52": "梦之钥·梦影可触",
            "53": "梦之钥·旧梦化牌",
            "54": "梦之钥·新梦结晶",
            "55": "梦之钥·愿力成线",
            "56": "梦之钥·梦境护主",
            "57": "梦之钥·迷局显形",
            "58": "梦之钥·梦光照界",
            "59": "梦之钥·钥心圆融",
            "60": "梦之钥·透明将现",
            "61": "透明牌·空白成形",
            "62": "透明牌·新牌缔约",
            "63": "透明牌·行动入手",
            "64": "透明牌·记录归页",
            "65": "透明牌·水源回应",
            "66": "透明牌·反射成镜",
            "67": "透明牌·引力听令",
            "68": "透明牌·梦境改写",
            "69": "透明牌·牌书新页",
            "70": "透明牌·谜局合拢",
            "71": "完整牌书·库洛归页",
            "72": "完整牌书·小樱归页",
            "73": "完整牌书·透明归页",
            "74": "完整牌书·守护归位",
            "75": "完整牌书·星梦同辉",
            "76": "完整牌书·牌灵列阵",
            "77": "完整牌书·魔阵无缺",
            "78": "完整牌书·愿力成界",
            "79": "完整牌书·世界应声",
            "80": "完整牌书·未来封存",
            "81": "星之守护·友枝晨光",
            "82": "星之守护·月峰护灯",
            "83": "星之守护·水族馆微澜",
            "84": "星之守护·企鹅公园风",
            "85": "星之守护·钟楼回声",
            "86": "星之守护·梦境巡游",
            "87": "星之守护·透明无痕",
            "88": "星之守护·守护成界",
            "89": "星之守护·万愿归心",
            "90": "星之守护·星光圆满",
            "91": "牌书主人·愿望不灭",
            "92": "牌书主人·日月同辉",
            "93": "牌书主人·旧牌安眠",
            "94": "牌书主人·新牌开花",
            "95": "牌书主人·梦钥入心",
            "96": "温柔世界·命运松手",
            "97": "温柔世界·诸牌同愿",
            "98": "温柔世界·未来改写",
            "99": "温柔世界·星梦不散",
            "100": "温柔世界·永恒之约",
        },
    },
}
