# 世界皮肤包名称数据文件。
# 这是“受限 Python 数据文件”，不是可执行插件：加载器只会读取 NAMES 这个字面量字典。
# 左侧键名是系统稳定 ID，不要改；右侧中文字符串才是皮肤包展示名。
# 本包按正式世界风格维护，尽量取原设定体系；只有粒度无法对齐时才用少量原创名缝合。
# 只允许写字典、列表、字符串、数字这类字面量；不要添加 import、函数调用、变量拼接或运行时代码。

NAMES = {
    "places": {
        "cities": {
            "city_tianshu": {
                "name": "石村",
                "terrain": "大荒村落",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_tianshu_01": "石村骨片", "trade_city_tianshu_02": "柳神嫩枝", "trade_city_tianshu_03": "兽奶陶罐"},
                "weapons": {
                    "liuguang_xijian": {"name": "柳神枝", "innate_skill": {"skill_id": "liuguang", "name": "柳神枝宝术"}},
                    "qiankun_pan": {"name": "鲲鹏羽", "innate_skill": {"skill_id": "qiankun", "name": "鲲鹏羽宝术"}},
                    "tianji_yuling": {"name": "原始真解", "innate_skill": {"skill_id": "tianji", "name": "原始真解宝术"}},
                    "xingheng_fuchen": {"name": "至尊骨", "innate_skill": {"skill_id": "xingheng", "name": "至尊骨宝术"}},
                    "qingxin_ling": {"name": "真龙爪", "innate_skill": {"skill_id": "qingxin", "name": "真龙爪宝术"}},
                    "yujing_fujian": {"name": "朱雀翎", "innate_skill": {"skill_id": "yujing", "name": "朱雀翎宝术"}},
                    "tianxiang_ling": {"name": "狻猊角", "innate_skill": {"skill_id": "tianxiang", "name": "狻猊角宝术"}},
                },
            },
            "city_qinglan": {
                "name": "虚神界",
                "terrain": "精神界",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_qinglan_01": "虚神界令", "trade_city_qinglan_02": "洞天碑拓", "trade_city_qinglan_03": "战榜残页"},
                "weapons": {
                    "qinglan_duanjian": {"name": "雷帝符", "innate_skill": {"skill_id": "fengren", "name": "雷帝符宝术"}},
                    "wuxiang_zhujian": {"name": "草字剑", "innate_skill": {"skill_id": "wuxiang", "name": "草字剑宝术"}},
                    "lanzhao_feiren": {"name": "六道轮回盘", "innate_skill": {"skill_id": "lanzhao", "name": "六道轮回盘宝术"}},
                    "qingzhu_dunren": {"name": "虚神界碑", "innate_skill": {"skill_id": "qingzhu_dun", "name": "虚神界碑宝术"}},
                    "qingteng_bi": {"name": "百断山钥", "innate_skill": {"skill_id": "qingteng", "name": "百断山钥宝术"}},
                    "youhuang_ling": {"name": "石国皇印", "innate_skill": {"skill_id": "youhuang", "name": "石国皇印宝术"}},
                    "mozhu_jian": {"name": "火国朱雀印", "innate_skill": {"skill_id": "mozhu", "name": "火国朱雀印宝术"}},
                },
            },
            "city_chixia": {
                "name": "补天阁",
                "terrain": "古教山门",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_chixia_01": "补天阁腰牌", "trade_city_chixia_02": "藏经骨书", "trade_city_chixia_03": "圣院香灰"},
                "weapons": {
                    "chixia_duandao": {"name": "补天阁令", "innate_skill": {"skill_id": "chixia", "name": "补天阁令宝术"}},
                    "chaohuo_qiang": {"name": "不老山符", "innate_skill": {"skill_id": "chaohuo", "name": "不老山符宝术"}},
                    "yanbei_nu": {"name": "仙古花", "innate_skill": {"skill_id": "yanbei", "name": "仙古花宝术"}},
                    "yandu_wandao": {"name": "长生药", "innate_skill": {"skill_id": "yandu", "name": "长生药宝术"}},
                    "dansha_feiren": {"name": "黑暗骨箭", "innate_skill": {"skill_id": "dansha", "name": "黑暗骨箭宝术"}},
                    "zhuyan_dao": {"name": "帝关战戟", "innate_skill": {"skill_id": "zhuyan", "name": "帝关战戟宝术"}},
                    "chilian_wandao": {"name": "边荒血旗", "innate_skill": {"skill_id": "chilian", "name": "边荒血旗宝术"}},
                },
            },
            "city_xuantie": {
                "name": "百断山",
                "terrain": "小世界山域",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_xuantie_01": "百断山钥", "trade_city_xuantie_02": "古兽牙牌", "trade_city_xuantie_03": "小世界沙"},
                "weapons": {
                    "xuantie_zhongji": {"name": "十凶骨", "innate_skill": {"skill_id": "bengshan", "name": "十凶骨宝术"}},
                    "zhenyue_fu": {"name": "天角蚁牙", "innate_skill": {"skill_id": "zhenyue", "name": "天角蚁牙宝术"}},
                    "heiyao_dunren": {"name": "麒麟角", "innate_skill": {"skill_id": "heiyao", "name": "麒麟角宝术"}},
                    "fanyue_pan": {"name": "真凰羽", "innate_skill": {"skill_id": "fanyue", "name": "真凰羽宝术"}},
                    "luxin_fu": {"name": "九叶剑草", "innate_skill": {"skill_id": "luxin", "name": "九叶剑草宝术"}},
                    "lingjiao_ji": {"name": "蛄族时骨", "innate_skill": {"skill_id": "lingjiao", "name": "蛄族时骨宝术"}},
                    "guming_dunren": {"name": "打神石", "innate_skill": {"skill_id": "guming", "name": "打神石宝术"}},
                },
            },
            "city_wanyao": {
                "name": "石国皇都",
                "terrain": "皇都",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_wanyao_01": "石国金券", "trade_city_wanyao_02": "皇都玉牒", "trade_city_wanyao_03": "石皇印拓"},
                "weapons": {
                    "wanyao_tengzhang": {"name": "小塔", "innate_skill": {"skill_id": "huichun", "name": "小塔宝术"}},
                    "lingfeng_bi": {"name": "轮回盘", "innate_skill": {"skill_id": "lingfeng", "name": "轮回盘宝术"}},
                    "yaowang_fuchen": {"name": "雷灵珠", "innate_skill": {"skill_id": "yaowang", "name": "雷灵珠宝术"}},
                    "fengwang_ling": {"name": "金翅大鹏羽", "innate_skill": {"skill_id": "fengwang", "name": "金翅大鹏羽宝术"}},
                    "lingmu_zhang": {"name": "黄金狮角", "innate_skill": {"skill_id": "lingmu", "name": "黄金狮角宝术"}},
                    "luming_qiang": {"name": "吞天雀羽", "innate_skill": {"skill_id": "luming", "name": "吞天雀羽宝术"}},
                    "zhupo_zhang": {"name": "穷奇牙", "innate_skill": {"skill_id": "zhupo", "name": "穷奇牙宝术"}},
                },
            },
            "city_yunmeng": {
                "name": "火国祖地",
                "terrain": "火域祖地",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_yunmeng_01": "火桑叶", "trade_city_yunmeng_02": "朱雀火羽", "trade_city_yunmeng_03": "火国铜符"},
                "weapons": {
                    "duannian_zhang": {"name": "魔葵籽", "innate_skill": {"skill_id": "duannian", "name": "魔葵籽宝术"}},
                    "mengwu_ling": {"name": "混沌古种", "innate_skill": {"skill_id": "mengwu", "name": "混沌古种宝术"}},
                    "shuijing_jian": {"name": "仙殿铜碑", "innate_skill": {"skill_id": "shuijing", "name": "仙殿铜碑宝术"}},
                    "nimeng_deng": {"name": "上界法旨", "innate_skill": {"skill_id": "nimeng", "name": "上界法旨宝术"}},
                    "jinghu_xijian": {"name": "三千州令", "innate_skill": {"skill_id": "jinghu", "name": "三千州令宝术"}},
                    "heishui_bi": {"name": "至尊殿残页", "innate_skill": {"skill_id": "heishui", "name": "至尊殿残页宝术"}},
                    "duhun_deng": {"name": "天神书院牌", "innate_skill": {"skill_id": "duhun", "name": "天神书院牌宝术"}},
                },
            },
            "city_liusha": {
                "name": "不老山",
                "terrain": "神山",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_liusha_01": "不老山令", "trade_city_liusha_02": "秦族玉简", "trade_city_liusha_03": "五行土"},
                "weapons": {
                    "liusha_feiren": {"name": "八域封印石", "innate_skill": {"skill_id": "shaying", "name": "八域封印石宝术"}},
                    "jueying_feijian": {"name": "虚道镜", "innate_skill": {"skill_id": "jueying", "name": "虚道镜宝术"}},
                    "duyun_wandao": {"name": "斩我剑", "innate_skill": {"skill_id": "duyun", "name": "斩我剑宝术"}},
                    "shajin_dao": {"name": "遁一舟", "innate_skill": {"skill_id": "shajin", "name": "遁一舟宝术"}},
                    "yingye_feiren": {"name": "神火灯", "innate_skill": {"skill_id": "yingye", "name": "神火灯宝术"}},
                    "langhao_feiren": {"name": "洞天环", "innate_skill": {"skill_id": "langhao", "name": "洞天环宝术"}},
                },
            },
            "city_hanshuang": {
                "name": "北海鲲鹏巢",
                "terrain": "北海巢域",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_hanshuang_01": "鲲鹏巢贝", "trade_city_hanshuang_02": "北海黑金", "trade_city_hanshuang_03": "阴阳羽"},
                "weapons": {
                    "xuehe_bi": {"name": "搬血鼎", "innate_skill": {"skill_id": "xueying", "name": "搬血鼎宝术"}},
                    "zhenhun_ling": {"name": "铭纹笔", "innate_skill": {"skill_id": "liehun", "name": "铭纹笔宝术"}},
                    "yueshi_wandao": {"name": "列阵旗", "innate_skill": {"skill_id": "yueshi", "name": "列阵旗宝术"}},
                    "hanyan_fuchen": {"name": "尊者符", "innate_skill": {"skill_id": "hanyan", "name": "尊者符宝术"}},
                    "yuehen_bi": {"name": "真一印", "innate_skill": {"skill_id": "yuehen", "name": "真一印宝术"}},
                    "chenyuan_dao": {"name": "圣祭鼓", "innate_skill": {"skill_id": "chenyuan", "name": "圣祭鼓宝术"}},
                },
            },
            "city_leize": {
                "name": "三千道州",
                "terrain": "道州",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_leize_01": "三千州路引", "trade_city_leize_02": "仙院帖", "trade_city_leize_03": "道州商契"},
                "weapons": {
                    "pojun_qiang": {"name": "天神矛", "innate_skill": {"skill_id": "pojun", "name": "天神矛宝术"}},
                    "leiguang_duanren": {"name": "仙王冠", "innate_skill": {"skill_id": "leiguang", "name": "仙王冠宝术"}},
                    "zidian_fu": {"name": "准仙帝钟", "innate_skill": {"skill_id": "zidian", "name": "准仙帝钟宝术"}},
                    "leihou_dunren": {"name": "荒天帝剑", "innate_skill": {"skill_id": "leihou", "name": "荒天帝剑宝术"}},
                    "guigen_dunren": {"name": "他化自在印", "innate_skill": {"skill_id": "guigen", "name": "他化自在印宝术"}},
                    "shouhun_ling": {"name": "独断万古碑", "innate_skill": {"skill_id": "shouhun", "name": "独断万古碑宝术"}},
                },
            },
            "city_bichao": {
                "name": "帝关",
                "terrain": "边关",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_bichao_01": "帝关战牌", "trade_city_bichao_02": "帝关军契", "trade_city_bichao_03": "黑暗骨箭"},
                "weapons": {
                    "xuangui_dunren": {"name": "青鳞鹰骨", "innate_skill": {"skill_id": "xuandun", "name": "青鳞鹰骨宝术"}},
                    "duanhai_jian": {"name": "火云雀翎", "innate_skill": {"skill_id": "duanhai", "name": "火云雀翎宝术"}},
                    "chaoxi_fuchen": {"name": "狈村狼牙", "innate_skill": {"skill_id": "chaoxi", "name": "狈村狼牙宝术"}},
                    "cangming_ji": {"name": "雨族符骨", "innate_skill": {"skill_id": "cangming", "name": "雨族符骨宝术"}},
                    "yingyue_pan": {"name": "石毅重瞳", "innate_skill": {"skill_id": "yingyue", "name": "石毅重瞳宝术"}},
                    "wumu_dunren": {"name": "月婵纱", "innate_skill": {"skill_id": "wumu", "name": "月婵纱宝术"}},
                },
            },
            "city_xingyun": {
                "name": "仙古遗地",
                "terrain": "仙古遗地",
                "roles": ["trade", "exploration", "city_state", "weapon_origin", "treasure_map", "wormhole_anchor"],
                "trade_goods": {"trade_city_xingyun_01": "仙古花契", "trade_city_xingyun_02": "长生药籽", "trade_city_xingyun_03": "古界石令"},
                "weapons": {
                    "zhuixing_nu": {"name": "清漪莲", "innate_skill": {"skill_id": "zhuixing", "name": "清漪莲宝术"}},
                    "chuanyun_lingqiang": {"name": "云曦玉", "innate_skill": {"skill_id": "chuanyun", "name": "云曦玉宝术"}},
                    "xingluo_fachen": {"name": "曹雨生阵盘", "innate_skill": {"skill_id": "xingluo", "name": "曹雨生阵盘宝术"}},
                    "yunxing_pan": {"name": "太阴玉兔铃", "innate_skill": {"skill_id": "yunxing", "name": "太阴玉兔铃宝术"}},
                    "jinlu_pan": {"name": "十冠王树苗", "innate_skill": {"skill_id": "jinlu", "name": "十冠王树苗宝术"}},
                    "zhuxie_qiang": {"name": "谪仙笛", "innate_skill": {"skill_id": "zhuxie", "name": "谪仙笛宝术"}},
                },
            },
        },
        "realm": {"realm_taixu": {"name": "百断山小世界", "terrain": "小世界秘境", "roles": ["secret_realm", "dynamic_battle"]}},
        "buyers": {
            "buyer_zhenyaosi": {"name": "石国镇妖府", "terrain": "皇朝官署", "roles": ["special_buyer", "war_prep"]},
            "buyer_fumodian": {"name": "补天伏魔院", "terrain": "古教法庭", "roles": ["special_buyer", "war_prep"]},
            "buyer_guishi": {"name": "虚神界鬼市", "terrain": "精神黑市", "roles": ["special_buyer", "war_prep"]},
            "buyer_longyuan": {"name": "真龙渊阁", "terrain": "真龙渊", "roles": ["special_buyer", "war_prep"]},
            "buyer_wanshou": {"name": "太古万兽盟", "terrain": "太古兽原", "roles": ["special_buyer", "war_prep"]},
            "buyer_pojun": {"name": "帝关破军营", "terrain": "边关军营", "roles": ["special_buyer", "war_prep"]},
        },
        "recycles": {
            "recycle_weapon": {"name": "石村炼器台", "terrain": "大荒石台", "roles": ["recycle"]},
            "recycle_gem": {"name": "虚神界鉴宝楼", "terrain": "精神宝楼", "roles": ["recycle"]},
            "recycle_book": {"name": "补天藏骨阁", "terrain": "古教骨阁", "roles": ["recycle"]},
        },
    },
    "world_items": {
        "medicine": {
            "material": {
                "world_med_xueqidan_1": "柳神露叶",
                "world_med_xueqidan_2": "百草液芽",
                "world_med_yinmingcao_1": "火桑花蕊",
                "world_med_yinmingcao_2": "北海灵藻",
                "world_med_huichunlu_1": "长生药须",
                "world_med_huichunlu_2": "仙古花粉",
                "world_med_ningshenlu_1": "石村药根",
                "world_med_ningshenlu_2": "朱雀血叶",
            },
            "catalyst": {
                "world_med_shenggudan_1": "真血骨泥",
                "world_med_shenggudan_2": "百断山赤石",
                "world_med_yanghundan_1": "补天阁药引",
                "world_med_yanghundan_2": "鲲鹏巢寒砂",
            },
            "fuel": {
                "world_med_xueqidan_3": "神火余炭",
                "world_med_yinmingcao_3": "朱雀炉灰",
                "world_med_huichunlu_3": "雷帝电砂",
                "world_med_ningshenlu_3": "柳木温炭",
                "world_med_shenggudan_3": "至尊骨屑",
                "world_med_yanghundan_3": "太古醒魂草",
            },
        },
        "life": {
            "chengshi": {
                "world_life_chengshi_1": "石村兽奶粮",
                "world_life_chengshi_2": "大荒粟",
                "world_life_chengshi_3": "火桑麦",
                "world_life_chengshi_4": "三千州灵豆",
                "world_life_chengshi_5": "帝关军粮",
            },
            "yanxian": {
                "world_life_yanxian_1": "北海盐晶",
                "world_life_yanxian_2": "大荒兽脯",
                "world_life_yanxian_3": "火国腊肉",
                "world_life_yanxian_4": "石国鱼干",
                "world_life_yanxian_5": "太古肉干",
            },
            "shuijing": {
                "world_life_shuijing_1": "柳神净泉",
                "world_life_shuijing_2": "北海澄石",
                "world_life_shuijing_3": "百断山滤砂",
                "world_life_shuijing_4": "补天清炭",
                "world_life_shuijing_5": "仙古甘露瓮",
            },
            "yibei": {
                "world_life_yibei_1": "火桑锦",
                "world_life_yibei_2": "大荒兽毡",
                "world_life_yibei_3": "石村麻线",
                "world_life_yibei_4": "帝关战毯",
                "world_life_yibei_5": "云曦玉棉",
            },
            "ranan": {
                "world_life_ranan_1": "神火灯芯",
                "world_life_ranan_2": "长明宝油",
                "world_life_ranan_3": "驱煞香",
                "world_life_ranan_4": "雷木脂",
                "world_life_ranan_5": "柳神安魂香",
            },
        },
        "build": {
            "jichu": {
                "world_build_jichu_1": "石村青石砖",
                "world_build_jichu_2": "补天阁木梁",
                "world_build_jichu_3": "帝关黑砖",
                "world_build_jichu_4": "北海玄泥",
                "world_build_jichu_5": "仙古鳞瓦",
            },
            "chengfang": {
                "world_build_chengfang_1": "帝关镇妖石",
                "world_build_chengfang_2": "柳神护城木",
                "world_build_chengfang_3": "惊兽宝铃",
                "world_build_chengfang_4": "太古拒马",
                "world_build_chengfang_5": "玄铁战闸",
            },
            "shuihuo": {
                "world_build_shuihuo_1": "北海导渠玉",
                "world_build_shuihuo_2": "寒泉骨管",
                "world_build_shuihuo_3": "朱雀避火砂",
                "world_build_shuihuo_4": "雷帝引雷桩",
                "world_build_shuihuo_5": "鲲鹏锁潮箍",
            },
            "zhenji": {
                "world_build_zhenji_1": "洞天阵砖",
                "world_build_zhenji_2": "聚灵骨砂",
                "world_build_zhenji_3": "封妖灰",
                "world_build_zhenji_4": "辟邪骨钉",
                "world_build_zhenji_5": "镇宅石锁",
            },
            "huashi": {
                "world_build_huashi_1": "补天琉檐",
                "world_build_huashi_2": "石国玉兽环",
                "world_build_huashi_3": "仙古云纹壁",
                "world_build_huashi_4": "月婵庭灯",
                "world_build_huashi_5": "三千州金坊",
            },
        },
        "relic": {
            "weiyun": {
                "world_relic_weiyun_1": "虚神界碎币",
                "world_relic_weiyun_2": "石国旧徽",
                "world_relic_weiyun_3": "百断山断钥",
                "world_relic_weiyun_4": "补天残页",
                "world_relic_weiyun_5": "柳神铜铃",
                "world_relic_weiyun_6": "失语镜砂",
                "world_relic_weiyun_7": "真龙骨片",
                "world_relic_weiyun_8": "北海舟钉",
            },
            "zhongyun": {
                "world_relic_zhongyun_1": "仙古圣杯",
                "world_relic_zhongyun_2": "银环星图",
                "world_relic_zhongyun_3": "界树枯种",
                "world_relic_zhongyun_4": "无面王冠",
                "world_relic_zhongyun_5": "北海罗盘",
                "world_relic_zhongyun_6": "封门骨典",
                "world_relic_zhongyun_7": "逆潮沙漏",
                "world_relic_zhongyun_8": "龙眠石碑",
            },
            "houyun": {
                "world_relic_houyun_1": "群星命轮",
                "world_relic_houyun_2": "旧神冠冕",
                "world_relic_houyun_3": "界门王钥",
                "world_relic_houyun_4": "终焉圣杯",
                "world_relic_houyun_5": "万象禁书",
                "world_relic_houyun_6": "昼夜双镜",
                "world_relic_houyun_7": "天灾方舟",
                "world_relic_houyun_8": "原初界标",
            },
        },
        "loot": {
            "yao": {
                "loot_yao_1": "遗种宝丹",
                "loot_yao_2": "遗种脊骨",
                "loot_yao_3": "遗种煞血",
                "loot_yao_4": "遗种甲皮",
                "loot_yao_5": "遗种瞳珠",
                "loot_yao_6": "遗种魂晶",
            },
            "mo": {"loot_mo_1": "黑暗魂核", "loot_mo_2": "魔魇角", "loot_mo_3": "黑血石", "loot_mo_4": "魔纹皮", "loot_mo_5": "裂魔爪", "loot_mo_6": "黑焰灰"},
            "gui": {
                "loot_gui_1": "阴魂珠",
                "loot_gui_2": "鬼火芯",
                "loot_gui_3": "残魂幡",
                "loot_gui_4": "白骨片",
                "loot_gui_5": "冥路纸",
                "loot_gui_6": "怨气瓶",
            },
            "long": {"loot_long_1": "真龙逆鳞", "loot_long_2": "龙须丝", "loot_long_3": "龙血石"},
            "shou": {
                "loot_shou_1": "狻猊兽筋",
                "loot_shou_2": "穷奇凶牙",
                "loot_shou_3": "遗种骨",
                "loot_shou_4": "兽纹皮",
                "loot_shou_5": "天角蚁角",
                "loot_shou_6": "兽魄心",
            },
            "bing": {
                "loot_bing_1": "帝关军魂印",
                "loot_bing_2": "破甲片",
                "loot_bing_3": "残兵符",
                "loot_bing_4": "边荒血旗",
                "loot_bing_5": "锈血铁",
                "loot_bing_6": "断寒刃",
            },
        },
    },
    "ring": {
        "recovery": {
            "fudai": "大荒福袋",
            "xueqidan": "真血契丹",
            "yinmingcao": "阴冥宝草",
            "huichunlu": "柳神回春露",
            "ningshenlu": "补天凝神露",
            "shenggudan": "至尊生骨丹",
            "yanghundan": "长生养魂丹",
        },
        "gems": {
            "huxinyu": "至尊护心玉",
            "xuangui shi": "玄龟宝石",
            "shanbi fozhu": "鲲鹏闪避珠",
            "mingxin fozhu": "重瞳明心珠",
            "huichun feicui": "柳神翡翠",
            "qingxin manao": "北海玛瑙",
            "qingshen shuijing": "金翅水晶",
            "jucai zijing": "七宝紫晶",
            "kangbao fuwen": "帝关抗暴纹",
        },
        "special": {"kaikongqi": "铭纹开窍石", "xisuiye": "至尊洗髓液", "cuifengdan": "神曦淬锋丹", "liuguang_qian": "神曦签"},
    },
    "weapons": {
        "skill_books": {
            "fengren_shu": "柳神骨书",
            "extreme_fengren_shu": "极·柳神骨书",
            "shaying_shu": "鲲鹏骨书",
            "extreme_shaying_shu": "极·鲲鹏骨书",
            "liuguang_shu": "原始真解骨书",
            "extreme_liuguang_shu": "极·原始真解骨书",
            "zhuixing_shu": "至尊骨骨书",
            "extreme_zhuixing_shu": "极·至尊骨骨书",
            "poxie_shu": "真龙骨书",
            "extreme_poxie_shu": "极·真龙骨书",
            "bengshan_shu": "朱雀骨书",
            "extreme_bengshan_shu": "极·朱雀骨书",
            "chuanyun_shu": "狻猊骨书",
            "extreme_chuanyun_shu": "极·狻猊骨书",
            "zhenyue_shu": "雷帝骨书",
            "extreme_zhenyue_shu": "极·雷帝骨书",
            "zhuoxin_shu": "草字剑骨书",
            "extreme_zhuoxin_shu": "极·草字剑骨书",
            "xueyu_shu": "六道骨书",
            "extreme_xueyu_shu": "极·六道骨书",
            "duyun_shu": "虚神界骨书",
            "extreme_duyun_shu": "极·虚神界骨书",
            "canyan_shu": "百断山骨书",
            "extreme_canyan_shu": "极·百断山骨书",
            "duannian_shu": "石国骨书",
            "extreme_duannian_shu": "极·石国骨书",
            "zhenhun_shu": "火国骨书",
            "extreme_zhenhun_shu": "极·火国骨书",
            "tianji_shu": "补天骨书",
            "extreme_tianji_shu": "极·补天骨书",
            "mengwu_shu": "不老山骨书",
            "extreme_mengwu_shu": "极·不老山骨书",
            "huichun_shu": "仙古骨书",
            "extreme_huichun_shu": "极·仙古骨书",
            "xuandun_shu": "长生药骨书",
            "extreme_xuandun_shu": "极·长生药骨书",
            "xueqi_shu": "黑暗骨书",
            "extreme_xueqi_shu": "极·黑暗骨书",
            "lingmu_shu": "帝关骨书",
            "extreme_lingmu_shu": "极·帝关骨书",
            "fanzhen_shu": "边荒骨书",
            "extreme_fanzhen_shu": "极·边荒骨书",
            "guiren_shu": "十凶骨书",
            "extreme_guiren_shu": "极·十凶骨书",
            "jieshi_shu": "天角蚁骨书",
            "extreme_jieshi_shu": "极·天角蚁骨书",
            "xuanyao_shu": "麒麟骨书",
            "extreme_xuanyao_shu": "极·麒麟骨书",
            "wuxiang_shu": "真凰骨书",
            "extreme_wuxiang_shu": "极·真凰骨书",
            "duanhai_shu": "九叶剑草骨书",
            "extreme_duanhai_shu": "极·九叶剑草骨书",
            "jueying_shu": "蛄族时骨骨书",
            "extreme_jueying_shu": "极·蛄族时骨骨书",
            "pojun_shu": "打神石骨书",
            "extreme_pojun_shu": "极·打神石骨书",
            "xingluo_shu": "小塔骨书",
            "extreme_xingluo_shu": "极·小塔骨书",
            "qiankun_shu": "轮回盘骨书",
            "extreme_qiankun_shu": "极·轮回盘骨书",
            "pozhen_shu": "雷灵骨书",
            "extreme_pozhen_shu": "极·雷灵骨书",
            "yujing_shu": "金鹏骨书",
            "extreme_yujing_shu": "极·金鹏骨书",
            "yueshi_shu": "黄金狮骨书",
            "extreme_yueshi_shu": "极·黄金狮骨书",
            "jinghu_shu": "吞天雀骨书",
            "extreme_jinghu_shu": "极·吞天雀骨书",
            "yingye_shu": "穷奇骨书",
            "extreme_yingye_shu": "极·穷奇骨书",
            "qingxin_shu": "魔葵骨书",
            "extreme_qingxin_shu": "极·魔葵骨书",
        },
        "types": {
            "axe": "宝斧",
            "balanced": "均衡宝具",
            "bell": "宝铃",
            "blade": "飞刃宝具",
            "crossbow": "宝弩",
            "dagger": "宝匕",
            "disc": "阵盘宝具",
            "halberd": "宝戟",
            "saber": "宝刀",
            "shield_blade": "盾刃宝具",
            "spear": "宝枪",
            "staff": "宝杖",
            "sword": "宝剑",
            "whisk": "拂尘宝具",
        },
    },
    "actors": {
        "monsters": {
            "qinglang": "青鳞狼妖",
            "huyao": "九尾狐妖",
            "shanzhu": "山猪遗种",
            "baigui": "白骨鬼",
            "shayan": "沙魇",
            "mopi_jiang": "黑暗魔将",
            "xuanling": "玄铁傀",
            "guijiang": "鬼火将",
            "hanpo": "寒魄鬼",
            "tiejia_bing": "铁甲残兵",
            "leishou": "雷兽",
            "yaotong_niao": "妖瞳鸦",
            "jiaolong": "蛟龙残影",
            "longxu_ying": "真龙须影",
            "mohun": "魔魂将",
            "moyan_shi": "魔焰使",
            "pojun": "破军残将",
            "duanren_jiang": "断刃军魂",
        },
        "physiques": {
            "fanti": {
                "name": "凡骨",
                "grade": "凡骨阶",
                "kind": "大荒",
                "desc": "凡骨显化大荒路线，肉身宝术对应原体质：平平无奇，却也最稳，所有玩家默认从这里开始。",
            },
            "qingfeng_lingti": {
                "name": "清风灵骨",
                "grade": "洞天灵骨",
                "kind": "鲲鹏",
                "desc": "清风灵骨显化鲲鹏路线，肉身宝术对应原体质：气息轻灵，稍微更容易避开伤害。",
            },
            "houde_lingti": {
                "name": "厚土灵骨",
                "grade": "洞天灵骨",
                "kind": "搬血",
                "desc": "厚土灵骨显化搬血路线，肉身宝术对应原体质：根基厚实，早期防御更稳。",
            },
            "lingquan_ti": {
                "name": "灵泉体",
                "grade": "洞天灵骨",
                "kind": "柳神",
                "desc": "灵泉体显化柳神路线，肉身宝术对应原体质：体内如有活泉，休息恢复更好。",
            },
            "tiegu_ti": {
                "name": "铁骨体",
                "grade": "洞天灵骨",
                "kind": "玄武",
                "desc": "铁骨体显化玄武路线，肉身宝术对应原体质：骨骼坚韧，承伤更稳。",
            },
            "mingxin_ti": {
                "name": "明心灵体",
                "grade": "洞天灵骨",
                "kind": "元神",
                "desc": "明心灵体显化元神路线，肉身宝术对应原体质：心神清明，精神上限略高。",
            },
            "qianye_lingti": {
                "name": "千叶灵体",
                "grade": "洞天灵骨",
                "kind": "祭灵",
                "desc": "千叶灵体显化祭灵路线，肉身宝术对应原体质：生机细密，血气和恢复都有一点优势。",
            },
            "qingmu_xuanti": {
                "name": "青木玄体",
                "grade": "铭纹宝骨",
                "kind": "祭灵",
                "desc": "青木玄体显化祭灵路线，肉身宝术对应原体质：偏生机恢复，跑商手续费略吃亏。",
            },
            "xuanbing_linggu": {
                "name": "玄冰灵骨",
                "grade": "铭纹宝骨",
                "kind": "冰凤",
                "desc": "玄冰灵骨显化冰凤路线，肉身宝术对应原体质：防御冷硬，恢复稍慢。",
            },
            "chixia_lingti": {
                "name": "赤霞灵体",
                "grade": "铭纹宝骨",
                "kind": "朱雀",
                "desc": "赤霞灵体显化朱雀路线，肉身宝术对应原体质：血气旺盛，精神上限略低。",
            },
            "leiwenzhanti": {
                "name": "雷纹战体",
                "grade": "铭纹宝骨",
                "kind": "雷帝",
                "desc": "雷纹战体显化雷帝路线，肉身宝术对应原体质：身法迅疾，生活经营不太细致。",
            },
            "yuyue_ti": {
                "name": "太阴玉体",
                "grade": "铭纹宝骨",
                "kind": "太阴",
                "desc": "太阴玉体显化太阴路线，肉身宝术对应原体质：精神与恢复突出，血气略薄。",
            },
            "jianxin_xuangu": {
                "name": "剑心玄骨",
                "grade": "铭纹宝骨",
                "kind": "剑胎",
                "desc": "剑心玄骨显化剑胎路线，肉身宝术对应原体质：适合冒险寻机，身板略薄。",
            },
            "longxiang_baoti": {
                "name": "龙象宝体",
                "grade": "列阵真血",
                "kind": "搬血",
                "desc": "龙象宝体显化搬血路线，肉身宝术对应原体质：血厚防稳，跑商不灵活。",
            },
            "xinghe_lingti": {
                "name": "星河灵体",
                "grade": "列阵真血",
                "kind": "星辰",
                "desc": "星河灵体显化星辰路线，肉身宝术对应原体质：擅长探险寻宝，防御略低。",
            },
            "taiyin_yuti": {
                "name": "太阴玉体真身",
                "grade": "列阵真血",
                "kind": "太阴",
                "desc": "太阴玉体真身显化太阴路线，肉身宝术对应原体质：恢复和精神很强，血气偏薄。",
            },
            "taiyang_yanti": {
                "name": "太阳炎体",
                "grade": "列阵真血",
                "kind": "朱雀",
                "desc": "太阳炎体显化朱雀路线，肉身宝术对应原体质：血气极盛，恢复和跑商略差。",
            },
            "canghai_daoti": {
                "name": "沧海道体",
                "grade": "列阵真血",
                "kind": "沧海",
                "desc": "沧海道体显化沧海路线，肉身宝术对应原体质：精神绵长、恢复平顺，防御偏弱。",
            },
            "wuyue_baoti": {
                "name": "五岳宝体",
                "grade": "列阵真血",
                "kind": "山宝",
                "desc": "五岳宝体显化山宝路线，肉身宝术对应原体质：防御厚重，精神和探险灵活性较差。",
            },
            "hunyuan_daoti": {
                "name": "玄黄镇岳体",
                "grade": "尊者道骨",
                "kind": "山宝",
                "desc": "玄黄镇岳体显化山宝路线，肉身宝术对应原体质：极端守御体质，精神与跑商是短板。",
            },
            "wugou_xianji": {
                "name": "琉璃无垢体",
                "grade": "尊者道骨",
                "kind": "无垢",
                "desc": "琉璃无垢体显化无垢路线，肉身宝术对应原体质：恢复与精神突出，正面承伤略弱。",
            },
            "wanxiang_lingtai": {
                "name": "千幻游身体",
                "grade": "尊者道骨",
                "kind": "鲲鹏",
                "desc": "千幻游身体显化鲲鹏路线，肉身宝术对应原体质：闪避和探险极强，血防明显偏薄。",
            },
            "zifu_tianti": {
                "name": "紫府明神体",
                "grade": "尊者道骨",
                "kind": "元神",
                "desc": "紫府明神体显化元神路线，肉身宝术对应原体质：精神海宽广，血气不是优势。",
            },
            "qianqiu_jianmai": {
                "name": "千秋剑脉",
                "grade": "尊者道骨",
                "kind": "剑胎",
                "desc": "千秋剑脉显化剑胎路线，肉身宝术对应原体质：适合险地寻剑，恢复不算出色。",
            },
            "shenxiao_leiti": {
                "name": "神霄雷体",
                "grade": "尊者道骨",
                "kind": "雷帝",
                "desc": "神霄雷体显化雷帝路线，肉身宝术对应原体质：迅烈难伤，恢复和跑商都粗糙。",
            },
            "xiantian_daotai": {
                "name": "先天药胎",
                "grade": "至尊仙骨",
                "kind": "柳神",
                "desc": "先天药胎显化柳神路线，肉身宝术对应原体质：恢复近乎夸张，但肉身承压偏弱。",
            },
            "canglong_shengti": {
                "name": "苍龙圣体",
                "grade": "至尊仙骨",
                "kind": "真龙",
                "desc": "苍龙圣体显化真龙路线，肉身宝术对应原体质：血气如海，精神和经营能力是短板。",
            },
            "jiuyao_shengti": {
                "name": "九曜星命体",
                "grade": "至尊仙骨",
                "kind": "星辰",
                "desc": "九曜星命体显化星辰路线，肉身宝术对应原体质：天生会找机会，适合探险和跑商，血防较薄。",
            },
            "bumie_jinshen": {
                "name": "不灭金身",
                "grade": "至尊仙骨",
                "kind": "不灭",
                "desc": "不灭金身显化不灭路线，肉身宝术对应原体质：最硬的防御路线，精神、探险和跑商都笨重。",
            },
            "taixu_xianmai": {
                "name": "太虚仙脉",
                "grade": "至尊仙骨",
                "kind": "虚神",
                "desc": "太虚仙脉显化虚神路线，肉身宝术对应原体质：飘忽难捉，探险极强，但正面血防很低。",
            },
            "hongmeng_xuanti": {
                "name": "归墟玄体",
                "grade": "至尊仙骨",
                "kind": "虚神",
                "desc": "归墟玄体显化虚神路线，肉身宝术对应原体质：精神深不可测，却不适合硬扛和经营。",
            },
        },
        "enemy_kinds": {
            "ancient_guard": "太古古卫",
            "beast": "遗种",
            "default": "凶煞",
            "demon": "黑暗魔",
            "demon_general": "魔将",
            "dragon": "真龙",
            "dragon_shadow": "龙影",
            "ghost": "鬼",
            "puppet": "傀",
            "soldier": "兵",
            "wandering_soul": "游魂",
            "yao": "妖",
            "yaojun": "妖君",
        },
        "enemy_skills": {
            "enemy_skill_yao_bite": "遗种撕咬",
            "enemy_skill_yaojun_shadow": "妖君裂影",
            "enemy_skill_beast_charge": "蛮兽冲撞",
            "enemy_skill_dragon_breath": "真龙吐息",
            "enemy_skill_dragon_shadow_breath": "龙影吐息",
            "enemy_skill_ghost_bite": "阴魂噬念",
            "enemy_skill_wandering_soul_bind": "游魂缠身",
            "enemy_skill_demon_flame": "魔焰灼心",
            "enemy_skill_demon_general_break": "魔将破阵",
            "enemy_skill_soldier_armor_break": "残兵破甲",
            "enemy_skill_ancient_guard_suppress": "古卫镇压",
            "enemy_skill_puppet_crush": "傀儡重压",
            "enemy_skill_default": "凶煞一击",
        },
    },
    "wormhole": {
        "bosses": {
            "worm_boss_01": "太古遗种·千刃界游王",
            "worm_boss_02": "太古遗种·陨炉泰坦",
            "worm_boss_03": "太古遗种·赤瘟炼狱君",
            "worm_boss_04": "太古遗种·缄魂巫皇",
            "worm_boss_05": "太古遗种·苍根不死王",
            "worm_boss_06": "太古遗种·回盾镜魔",
            "worm_boss_07": "太古遗种·断星斩王",
            "worm_boss_08": "太古遗种·星环仲裁者",
        },
        "flows": {
            "worm_flow_swift": "鲲鹏连击",
            "worm_flow_heavy": "至尊骨破防",
            "worm_flow_dot": "朱雀持续灼烧",
            "worm_flow_control": "六道压制",
            "worm_flow_survival": "柳神续航",
            "worm_flow_counter": "轮回反击",
            "worm_flow_execute": "草字剑斩杀",
            "worm_flow_leader": "帝关协作",
        },
        "war_prep_bosses": {
            "war_boss_zhenyaosi_01": "百臂青妖王",
            "war_boss_zhenyaosi_02": "裂巢迅影后",
            "war_boss_zhenyaosi_03": "万爪潮主",
            "war_boss_fumodian_01": "黑铠破界魔",
            "war_boss_fumodian_02": "焚契魔侯",
            "war_boss_fumodian_03": "坠岳魔君",
            "war_boss_guishi_01": "无灯冥契主",
            "war_boss_guishi_02": "缚魂夜巫",
            "war_boss_guishi_03": "纸城鬼王",
            "war_boss_longyuan_01": "逆鳞界龙君",
            "war_boss_longyuan_02": "潮骸古蛟",
            "war_boss_longyuan_03": "星渊断角龙",
            "war_boss_wanshou_01": "荒骨兽神",
            "war_boss_wanshou_02": "苍鬃不死兽",
            "war_boss_wanshou_03": "万蹄裂阵王",
            "war_boss_pojun_01": "星甲破阵帅",
            "war_boss_pojun_02": "断旗兵主",
            "war_boss_pojun_03": "铁潮军魂王",
        },
        "war_prep_affixes": {
            "war_prep_affix_exposed_nest": "残巢已露",
            "war_prep_affix_half_open_gate": "古门半开",
            "war_prep_affix_war_marks": "战痕回涌",
            "war_prep_affix_warm_embers": "余烬未冷",
            "war_prep_affix_gathering_enemies": "群敌聚形",
            "war_prep_affix_unstable_rift": "裂口不稳",
        },
    },
    "secret_realm": {
        "environments": {
            "secret_env_youming_wind": {"name": "幽冥罡风", "desc": "阴风压魂，怪物精神压迫更重。"},
            "secret_env_mirror_sky": {"name": "镜天宝影", "desc": "镜影错乱，遭遇强度起伏更大。"},
            "secret_env_dragon_bone_dust": {"name": "真龙骨尘", "desc": "龙骨尘暴翻涌，怪物血防更厚。"},
            "secret_env_star_fire_rain": {"name": "星火劫雨", "desc": "星火落如雨，怪物攻势更烈。"},
            "secret_env_returning_tide": {"name": "归墟古潮", "desc": "归墟潮汐反复，战斗更拖长。"},
        }
    },
    "system": {
        "quality": {"quality_common": "凡骨", "quality_good": "宝骨", "quality_rare": "至尊骨", "quality_epic": "仙骨"},
        "currency": {"raw_stones": "精璧"},
        "levels": {
            "1": "搬血·蛮力初醒",
            "2": "搬血·血气如泉",
            "3": "搬血·筋骨雷鸣",
            "4": "搬血·神曦炼体",
            "5": "搬血·极境叩门",
            "6": "洞天·灵窍初开",
            "7": "洞天·宝光成轮",
            "8": "洞天·洞天养灵",
            "9": "洞天·诸洞相映",
            "10": "洞天·万灵归一",
            "11": "化灵·灵身初醒",
            "12": "化灵·真灵入骨",
            "13": "化灵·神形自照",
            "14": "化灵·宝术入魂",
            "15": "化灵·脱胎换骨",
            "16": "铭纹·骨文初铭",
            "17": "铭纹·符纹入体",
            "18": "铭纹·宝纹成阵",
            "19": "铭纹·万法刻身",
            "20": "铭纹·骨书成章",
            "21": "列阵·阵纹初列",
            "22": "列阵·杀阵入骨",
            "23": "列阵·诸阵相扣",
            "24": "列阵·天地入阵",
            "25": "列阵·阵破诸敌",
            "26": "尊者·尊威初显",
            "27": "尊者·一念压敌",
            "28": "尊者·宝术随心",
            "29": "尊者·尊域成形",
            "30": "尊者·神火将燃",
            "31": "神火·道火初燃",
            "32": "神火·心火照魂",
            "33": "神火·火种护道",
            "34": "神火·神焰不灭",
            "35": "神火·真一在望",
            "36": "真一·真意初成",
            "37": "真一·身魂合一",
            "38": "真一·道种入心",
            "39": "真一·万法归真",
            "40": "真一·圣祭将临",
            "41": "圣祭·祭纹初亮",
            "42": "圣祭·圣血归炉",
            "43": "圣祭·祭灵回应",
            "44": "圣祭·天地受祭",
            "45": "圣祭·天神在望",
            "46": "天神·神威初临",
            "47": "天神·天命加身",
            "48": "天神·神识映空",
            "49": "天神·神威压界",
            "50": "天神·虚道将开",
            "51": "虚道·触道入虚",
            "52": "虚道·虚空留痕",
            "53": "虚道·道音入骨",
            "54": "虚道·身入大道",
            "55": "虚道·斩我将启",
            "56": "斩我·明我本心",
            "57": "斩我·斩却旧执",
            "58": "斩我·重塑真身",
            "59": "斩我·道心无垢",
            "60": "斩我·遁一将临",
            "61": "遁一·寻一入道",
            "62": "遁一·守一不失",
            "63": "遁一·破一见真",
            "64": "遁一·归一成势",
            "65": "遁一·至尊在望",
            "66": "至尊·人道绝巅",
            "67": "至尊·诸天共尊",
            "68": "至尊·帝路开门",
            "69": "至尊·仙光初照",
            "70": "至尊·真仙将临",
            "71": "真仙·仙气入骨",
            "72": "真仙·长生门开",
            "73": "真仙·真仙立道",
            "74": "真仙·万劫不朽",
            "75": "仙王·王座初临",
            "76": "仙王·俯看纪元",
            "77": "仙王·仙域震动",
            "78": "仙王·巨头气象",
            "79": "准仙帝·帝光初照",
            "80": "准仙帝·一滴血乱古",
            "81": "准仙帝·帝法压世",
            "82": "准仙帝·黑暗对岸",
            "83": "仙帝·帝位成真",
            "84": "仙帝·诸天共尊",
            "85": "仙帝·万古独照",
            "86": "仙帝·荒剑开天",
            "87": "祭道·祭尽旧身",
            "88": "祭道·诸法成灰",
            "89": "祭道·道火照古今",
            "90": "祭道·祭道圆满",
            "91": "祭道之上·超脱路现",
            "92": "祭道之上·岁月归掌",
            "93": "祭道之上·诸世成环",
            "94": "祭道之上·高原回望",
            "95": "祭道之上·万古归一",
            "96": "帝路尽头·他化自在",
            "97": "帝路尽头·一剑隔世",
            "98": "帝路尽头·独断万古",
            "99": "帝路尽头·诸世归真",
            "100": "帝路尽头·万古唯一",
        },
    },
}
