"""修仙模块基础数值。

这里只放全局常量。玩法逻辑写在各组件 service.py，避免根目录反向依赖子组件。
"""

from __future__ import annotations


SCHEMA_VERSION = 2026062901
DAY_RESET_HOUR = 4
MAX_LEVEL = 100
SECT_LEVEL_MAX = 100
CITY_MAX_LEVEL = 107
REST_FAST_SECONDS = 60
REST_FULL_MINUTES = 30
BATTLE_RECORD_RETENTION_DAYS = 5
DIRECT_FLOW_RETENTION_DAYS = 7
NEWSPAPER_RETENTION_DAYS = 7
WORLD_SHORT_RECORD_RETENTION_DAYS = 5
WORLD_LONG_RECORD_RETENTION_DAYS = 7
MESSAGE_FLOW_RETENTION_DAYS = 2
MESSAGE_FLOW_MAX_ROWS = 5000
MESSAGE_FLOW_GLOBAL_BUFFER = 3000
MESSAGE_FLOW_PER_PLAYER_BUFFER = 300
DONGTIAN_CODE_TTL_MINUTES = 10
DONGTIAN_CODE_RETENTION_DAYS = 7
DONGTIAN_GAME_TOKEN_TTL_HOURS = 24
DONGTIAN_ROUND_TTL_MINUTES = 15
DONGTIAN_ROUND_MIN_SECONDS = 10
DONGTIAN_REWARD_DECAY = 0.055
DONGTIAN_MIN_REWARD_RATE = 0.45
YUANQI_CODE_TTL_HOURS = 24
YUANQI_VOUCHER_KEY = "yuanqi_voucher"
PLAYER_EXP_POWER_BASE = 120
PLAYER_EXP_LEVEL_BASE = 600
WEAPON_EXP_POWER_BASE = 40
WEAPON_EXP_LEVEL_BASE = 200
EXP_CURVE_POWER = 1.85
EXP_LATE_START_LEVEL = 40
EXP_LATE_PROGRESS_SPAN = 59
EXP_LATE_MID_FACTOR = 8
EXP_LATE_HIGH_FACTOR = 12
EXP_LATE_END_FACTOR = 18
EXP_LATE_MID_POWER = 1.35
EXP_LATE_HIGH_POWER = 2.4
EXP_LATE_END_POWER = 4.0
WEAPON_EXP_PER_ACTION = 10
WEAPON_EXP_ACTION_BONUS_RATE = 0.33
WEAPON_EXP_NO_ACTION_FLOOR_RATE = 0.65
WEAPON_EXP_LEVEL_UP_STEP = 0.035
WEAPON_EXP_LEVEL_DOWN_STEP = 0.025
WEAPON_EXP_LEVEL_UP_CAP = 1.85
WEAPON_EXP_LEVEL_DOWN_FLOOR = 0.65
WEAPON_EXP_DEALT_WEIGHT = 0.28
WEAPON_EXP_TAKEN_WEIGHT = 0.22
WEAPON_EXP_DEALT_RATIO_CAP = 1.35
WEAPON_EXP_TAKEN_RATIO_CAP = 1.10
TRADE_PROFIT_PLAYER_PRESSURE_WEIGHT = 0.75
TRADE_PROFIT_GLOBAL_PRESSURE_WEIGHT = 0.25
TRADE_PROFIT_PRESSURE_FACTOR = 0.45
SPECIAL_SELL_PRESSURE_FACTOR = 0.45
WEAPON_RECYCLE_PRESSURE_FACTOR = 0.75
GEM_RECYCLE_PRESSURE_FACTOR = 0.65
BOOK_RECYCLE_PRESSURE_FACTOR = 0.65


# ----------------------------
# 玩家
# ----------------------------


DEFAULT_LOCATION_ID = "city_tianshu"
DEFAULT_LOCATION = "天枢城"
DEFAULT_BACKPACK_LIMIT = 80
DEFAULT_WEIGHT_LIMIT = 500
RENAME_COOLDOWN_HOURS = 24
NEWBIE_GIFT_STONES = 10_000
WISH_TOKEN_ITEM_ID = "liuguang_qian"
WORLD_COORD_MIN = -100
WORLD_COORD_MAX = 100


# ----------------------------
# 银行
# ----------------------------


# 低星级给更高收益比例，让前期存钱有体感；高星级给更高收益总量，
# 但比例逐步降低，避免后期只靠银行被动收益压过主动玩法。
BANK_LEVELS = {
    1: {"name": "一星", "limit": 100_000, "cost": 0, "daily_interest_limit": 8_000, "hour_rate": 0.0033},
    2: {"name": "二星", "limit": 300_000, "cost": 50_000, "daily_interest_limit": 18_000, "hour_rate": 0.0025},
    3: {"name": "三星", "limit": 800_000, "cost": 180_000, "daily_interest_limit": 40_000, "hour_rate": 0.0020},
    4: {"name": "四星", "limit": 2_000_000, "cost": 600_000, "daily_interest_limit": 75_000, "hour_rate": 0.00155},
    5: {"name": "五星", "limit": 5_000_000, "cost": 1_800_000, "daily_interest_limit": 135_000, "hour_rate": 0.0011},
    6: {"name": "六星", "limit": 12_000_000, "cost": 5_000_000, "daily_interest_limit": 215_000, "hour_rate": 0.00072},
    7: {"name": "七星", "limit": 30_000_000, "cost": 15_000_000, "daily_interest_limit": 320_000, "hour_rate": 0.00044},
}
BANK_MAX_LEVEL = 7


# ----------------------------
# 商场 / 市场
# ----------------------------


MARKET_FEE_RATE = 0.05
TRADE_BUY_FEE_RATE = 0.01
TRADE_SELL_FEE_RATE = 0.02
TRADE_RESALE_LOCK_HOURS = 4
TRADE_MAX_PROFIT_RATE = 0.45
TRADE_PURE_ECONOMY_PRICE_FACTOR = 1.18
TRADE_DAILY_REWARD_MIN_QUANTITY = 5
TRADE_DAILY_REWARD_MIN_NET = 8_000
TRADE_DAILY_REWARD_RATE = 0.035
TRADE_DAILY_REWARD_CAP_BASE = 2_000
TRADE_DAILY_REWARD_CAP_LEVEL_BONUS = 350
TRADE_DAILY_REWARD_QUANTITY_SOFT_RATE = 0.08
TRADE_DAILY_REWARD_NET_SOFT_RATE = 0.10
TRADE_ACTIVE_WINDOW_DAYS = 7
TRADE_DAILY_SOFT_BASE_QUANTITY = 80
TRADE_DAILY_SOFT_PER_ACTIVE_QUANTITY = 80
TRADE_DAILY_PLAYER_SOFT_MIN_QUANTITY = 40
TRADE_DAILY_PLAYER_SOFT_SHARE_MULTIPLIER = 1.8
TRADE_DAILY_PLAYER_SOFT_MAX_SHARE = 0.45
TRADE_DAILY_PROFIT_MIN_RATE = 0.35
SPECIAL_SELL_SOFT_BASE = 50_000
SPECIAL_SELL_SOFT_LEVEL_BONUS = 15_000
SPECIAL_SELL_MIN_RATE = 0.35
BOOK_RECYCLE_SOFT_BASE = 12_000
BOOK_RECYCLE_SOFT_LEVEL_BONUS = 4_000
BOOK_RECYCLE_MIN_RATE = 0.25
BOOK_RECYCLE_SINGLE_CAP_BASE = 5_000
BOOK_RECYCLE_SINGLE_CAP_LEVEL_BONUS = 900
WEAPON_RECYCLE_SOFT_BASE = 20_000
WEAPON_RECYCLE_SOFT_LEVEL_BONUS = 8_000
WEAPON_RECYCLE_MIN_RATE = 0.25
WEAPON_RECYCLE_SINGLE_CAP_BASE = 12_000
WEAPON_RECYCLE_SINGLE_CAP_LEVEL_BONUS = 1_800
GEM_RECYCLE_SOFT_BASE = 12_000
GEM_RECYCLE_SOFT_LEVEL_BONUS = 4_000
GEM_RECYCLE_MIN_RATE = 0.25
GEM_RECYCLE_SINGLE_CAP_BASE = 4_000
GEM_RECYCLE_SINGLE_CAP_LEVEL_BONUS = 700

FIXED_EQUIPMENT_SLOT_FACTORS = {
    "头部": 1.0,
    "左手": 0.9,
    "右手": 0.9,
    "左脚": 0.8,
    "右脚": 0.8,
    "饰品": 1.2,
    "护甲": 1.5,
}
EQUIPMENT_DEFAULT_HOLES = 3
EQUIPMENT_MAX_HOLES = 9


# ----------------------------
# 探险 / 战斗
# ----------------------------


EXPLORE_MINUTES = 30
ENCOUNTER_SECONDS = 90
PLAYER_BASE_ATTACK = 5
WORMHOLE_DURATION_MINUTES = 60
WORMHOLE_CHALLENGE_COOLDOWN_MINUTES = 3
WORMHOLE_NOTICE_COOLDOWN_MINUTES = 5
WORMHOLE_ACTIVE_WINDOW_DAYS = 7
WORMHOLE_DAILY_MIN_LIMIT = 2
WORMHOLE_DAILY_BASE_LIMIT = 2
WORMHOLE_DAILY_ACTIVE_PLAYER_STEP = 4
WORMHOLE_DAILY_MAX_LIMIT = 8
SEASONAL_BOSS_CHALLENGE_COOLDOWN_MINUTES = 30
SEASONAL_BOSS_MAX_CHALLENGES = 5
WEAPON_TYPE_INTERVAL_FACTORS = {
    "dagger": 0.78,
    "blade": 0.82,
    "sword": 0.93,
    "bell": 0.9,
    "saber": 1.0,
    "crossbow": 1.04,
    "whisk": 1.0,
    "staff": 1.08,
    "spear": 1.12,
    "shield_blade": 1.15,
    "halberd": 1.22,
    "disc": 1.24,
    "axe": 1.3,
}


EQUIPMENT_SLOTS = ("头部", "左手", "右手", "左脚", "右脚", "饰品", "护甲")


__all__ = [
    "BANK_LEVELS",
    "BANK_MAX_LEVEL",
    "BATTLE_RECORD_RETENTION_DAYS",
    "BOOK_RECYCLE_MIN_RATE",
    "BOOK_RECYCLE_SINGLE_CAP_BASE",
    "BOOK_RECYCLE_SINGLE_CAP_LEVEL_BONUS",
    "BOOK_RECYCLE_SOFT_BASE",
    "BOOK_RECYCLE_SOFT_LEVEL_BONUS",
    "CITY_MAX_LEVEL",
    "DAY_RESET_HOUR",
    "DEFAULT_BACKPACK_LIMIT",
    "DEFAULT_LOCATION_ID",
    "DEFAULT_LOCATION",
    "DEFAULT_WEIGHT_LIMIT",
    "DIRECT_FLOW_RETENTION_DAYS",
    "DONGTIAN_CODE_RETENTION_DAYS",
    "DONGTIAN_CODE_TTL_MINUTES",
    "DONGTIAN_GAME_TOKEN_TTL_HOURS",
    "DONGTIAN_MIN_REWARD_RATE",
    "DONGTIAN_ROUND_MIN_SECONDS",
    "DONGTIAN_ROUND_TTL_MINUTES",
    "DONGTIAN_REWARD_DECAY",
    "YUANQI_CODE_TTL_HOURS",
    "YUANQI_VOUCHER_KEY",
    "ENCOUNTER_SECONDS",
    "EQUIPMENT_DEFAULT_HOLES",
    "EQUIPMENT_MAX_HOLES",
    "EQUIPMENT_SLOTS",
    "EXP_CURVE_POWER",
    "EXP_LATE_END_FACTOR",
    "EXP_LATE_END_POWER",
    "EXP_LATE_HIGH_FACTOR",
    "EXP_LATE_HIGH_POWER",
    "EXP_LATE_MID_FACTOR",
    "EXP_LATE_MID_POWER",
    "EXP_LATE_PROGRESS_SPAN",
    "EXP_LATE_START_LEVEL",
    "EXPLORE_MINUTES",
    "FIXED_EQUIPMENT_SLOT_FACTORS",
    "GEM_RECYCLE_MIN_RATE",
    "GEM_RECYCLE_PRESSURE_FACTOR",
    "GEM_RECYCLE_SINGLE_CAP_BASE",
    "GEM_RECYCLE_SINGLE_CAP_LEVEL_BONUS",
    "GEM_RECYCLE_SOFT_BASE",
    "GEM_RECYCLE_SOFT_LEVEL_BONUS",
    "MARKET_FEE_RATE",
    "MAX_LEVEL",
    "MESSAGE_FLOW_GLOBAL_BUFFER",
    "MESSAGE_FLOW_MAX_ROWS",
    "MESSAGE_FLOW_PER_PLAYER_BUFFER",
    "MESSAGE_FLOW_RETENTION_DAYS",
    "NEWBIE_GIFT_STONES",
    "NEWSPAPER_RETENTION_DAYS",
    "PLAYER_BASE_ATTACK",
    "PLAYER_EXP_LEVEL_BASE",
    "PLAYER_EXP_POWER_BASE",
    "RENAME_COOLDOWN_HOURS",
    "REST_FAST_SECONDS",
    "REST_FULL_MINUTES",
    "SCHEMA_VERSION",
    "SEASONAL_BOSS_CHALLENGE_COOLDOWN_MINUTES",
    "SEASONAL_BOSS_MAX_CHALLENGES",
    "SECT_LEVEL_MAX",
    "SPECIAL_SELL_MIN_RATE",
    "SPECIAL_SELL_PRESSURE_FACTOR",
    "SPECIAL_SELL_SOFT_BASE",
    "SPECIAL_SELL_SOFT_LEVEL_BONUS",
    "TRADE_BUY_FEE_RATE",
    "TRADE_ACTIVE_WINDOW_DAYS",
    "TRADE_DAILY_PROFIT_MIN_RATE",
    "TRADE_DAILY_PLAYER_SOFT_MAX_SHARE",
    "TRADE_DAILY_PLAYER_SOFT_MIN_QUANTITY",
    "TRADE_DAILY_PLAYER_SOFT_SHARE_MULTIPLIER",
    "TRADE_DAILY_SOFT_BASE_QUANTITY",
    "TRADE_DAILY_SOFT_PER_ACTIVE_QUANTITY",
    "TRADE_DAILY_REWARD_CAP_BASE",
    "TRADE_DAILY_REWARD_CAP_LEVEL_BONUS",
    "TRADE_DAILY_REWARD_MIN_NET",
    "TRADE_DAILY_REWARD_MIN_QUANTITY",
    "TRADE_DAILY_REWARD_NET_SOFT_RATE",
    "TRADE_DAILY_REWARD_QUANTITY_SOFT_RATE",
    "TRADE_DAILY_REWARD_RATE",
    "TRADE_MAX_PROFIT_RATE",
    "TRADE_PURE_ECONOMY_PRICE_FACTOR",
    "TRADE_PROFIT_GLOBAL_PRESSURE_WEIGHT",
    "TRADE_PROFIT_PLAYER_PRESSURE_WEIGHT",
    "TRADE_PROFIT_PRESSURE_FACTOR",
    "TRADE_RESALE_LOCK_HOURS",
    "TRADE_SELL_FEE_RATE",
    "WEAPON_TYPE_INTERVAL_FACTORS",
    "WEAPON_EXP_ACTION_BONUS_RATE",
    "WEAPON_EXP_DEALT_RATIO_CAP",
    "WEAPON_EXP_DEALT_WEIGHT",
    "WEAPON_EXP_LEVEL_DOWN_FLOOR",
    "WEAPON_EXP_LEVEL_DOWN_STEP",
    "WEAPON_EXP_LEVEL_UP_CAP",
    "WEAPON_EXP_LEVEL_UP_STEP",
    "WEAPON_EXP_NO_ACTION_FLOOR_RATE",
    "WEAPON_EXP_PER_ACTION",
    "WEAPON_EXP_POWER_BASE",
    "WEAPON_EXP_LEVEL_BASE",
    "WEAPON_EXP_TAKEN_RATIO_CAP",
    "WEAPON_EXP_TAKEN_WEIGHT",
    "WEAPON_RECYCLE_MIN_RATE",
    "WEAPON_RECYCLE_PRESSURE_FACTOR",
    "WEAPON_RECYCLE_SINGLE_CAP_BASE",
    "WEAPON_RECYCLE_SINGLE_CAP_LEVEL_BONUS",
    "WEAPON_RECYCLE_SOFT_BASE",
    "WEAPON_RECYCLE_SOFT_LEVEL_BONUS",
    "WISH_TOKEN_ITEM_ID",
    "WORMHOLE_ACTIVE_WINDOW_DAYS",
    "WORMHOLE_CHALLENGE_COOLDOWN_MINUTES",
    "WORMHOLE_DAILY_ACTIVE_PLAYER_STEP",
    "WORMHOLE_DAILY_BASE_LIMIT",
    "WORMHOLE_DAILY_MIN_LIMIT",
    "WORMHOLE_DAILY_MAX_LIMIT",
    "WORMHOLE_DURATION_MINUTES",
    "WORMHOLE_NOTICE_COOLDOWN_MINUTES",
    "WORLD_LONG_RECORD_RETENTION_DAYS",
    "WORLD_COORD_MAX",
    "WORLD_COORD_MIN",
    "WORLD_SHORT_RECORD_RETENTION_DAYS",
]
