# 世界皮肤包名称数据文件。
# 这是“受限 Python 数据文件”，不是可执行插件：加载器只会读取 NAMES 这个字面量字典。
# 左侧键名是系统稳定 ID，不要改；右侧中文字符串才是皮肤包展示名。
# 本包按正式世界风格维护，尽量取原设定体系；只有粒度无法对齐时才用少量原创名缝合。
# 只允许写字典、列表、字符串、数字这类字面量；不要添加 import、函数调用、变量拼接或运行时代码。

NAMES = {'places': {'cities': {'city_tianshu': {'name': '圣魂村',
                                        'terrain': '村落',
                                        'roles': ['trade',
                                                  'exploration',
                                                  'city_state',
                                                  'weapon_origin',
                                                  'treasure_map',
                                                  'wormhole_anchor'],
                                        'trade_goods': {'trade_city_tianshu_01': '蓝银草束',
                                                        'trade_city_tianshu_02': '村铁锄',
                                                        'trade_city_tianshu_03': '觉醒石票'},
                                        'weapons': {'liuguang_xijian': {'name': '蓝银草武魂',
                                                                        'innate_skill': {'skill_id': 'liuguang',
                                                                                         'name': '蓝银草魂技'}},
                                                    'qiankun_pan': {'name': '昊天锤武魂',
                                                                    'innate_skill': {'skill_id': 'qiankun',
                                                                                     'name': '昊天锤魂技'}},
                                                    'tianji_yuling': {'name': '柔骨兔武魂',
                                                                      'innate_skill': {'skill_id': 'tianji',
                                                                                       'name': '柔骨兔魂技'}},
                                                    'xingheng_fuchen': {'name': '邪眸白虎武魂',
                                                                        'innate_skill': {'skill_id': 'xingheng',
                                                                                         'name': '邪眸白虎魂技'}},
                                                    'qingxin_ling': {'name': '幽冥灵猫武魂',
                                                                     'innate_skill': {'skill_id': 'qingxin',
                                                                                      'name': '幽冥灵猫魂技'}},
                                                    'yujing_fujian': {'name': '香肠武魂',
                                                                      'innate_skill': {'skill_id': 'yujing',
                                                                                       'name': '香肠专卖魂技'}},
                                                    'tianxiang_ling': {'name': '七宝琉璃塔武魂',
                                                                       'innate_skill': {'skill_id': 'tianxiang',
                                                                                        'name': '七宝琉璃塔魂技'}}}},
                       'city_qinglan': {'name': '诺丁学院',
                                        'terrain': '学院',
                                        'roles': ['trade',
                                                  'exploration',
                                                  'city_state',
                                                  'weapon_origin',
                                                  'treasure_map',
                                                  'wormhole_anchor'],
                                        'trade_goods': {'trade_city_qinglan_01': '诺丁校徽',
                                                        'trade_city_qinglan_02': '大师手札',
                                                        'trade_city_qinglan_03': '初级魂师证'},
                                        'weapons': {'qinglan_duanjian': {'name': '邪火凤凰武魂',
                                                                         'innate_skill': {'skill_id': 'fengren',
                                                                                          'name': '邪火凤凰魂技'}},
                                                    'wuxiang_zhujian': {'name': '蓝电霸王龙武魂',
                                                                        'innate_skill': {'skill_id': 'wuxiang',
                                                                                         'name': '蓝电霸王龙魂技'}},
                                                    'lanzhao_feiren': {'name': '碧磷蛇皇武魂',
                                                                       'innate_skill': {'skill_id': 'lanzhao',
                                                                                        'name': '碧磷蛇皇魂技'}},
                                                    'qingzhu_dunren': {'name': '九心海棠武魂',
                                                                       'innate_skill': {'skill_id': 'qingzhu_dun',
                                                                                        'name': '九心海棠魂技'}},
                                                    'qingteng_bi': {'name': '六翼天使武魂',
                                                                    'innate_skill': {'skill_id': 'qingteng',
                                                                                     'name': '六翼天使魂技'}},
                                                    'youhuang_ling': {'name': '海神三叉戟',
                                                                      'innate_skill': {'skill_id': 'youhuang',
                                                                                       'name': '海神三叉戟魂技'}},
                                                    'mozhu_jian': {'name': '修罗魔剑',
                                                                   'innate_skill': {'skill_id': 'mozhu',
                                                                                    'name': '修罗魔剑魂技'}}}},
                       'city_chixia': {'name': '索托城',
                                       'terrain': '城镇',
                                       'roles': ['trade',
                                                 'exploration',
                                                 'city_state',
                                                 'weapon_origin',
                                                 'treasure_map',
                                                 'wormhole_anchor'],
                                       'trade_goods': {'trade_city_chixia_01': '大斗魂徽章',
                                                       'trade_city_chixia_02': '索托门票',
                                                       'trade_city_chixia_03': '玫瑰酒店券'},
                                       'weapons': {'chixia_duandao': {'name': '八蛛矛外附魂骨',
                                                                      'innate_skill': {'skill_id': 'chixia',
                                                                                       'name': '八蛛矛魂技'}},
                                                   'chaohuo_qiang': {'name': '诸葛神弩武魂',
                                                                     'innate_skill': {'skill_id': 'chaohuo',
                                                                                      'name': '诸葛神弩魂技'}},
                                                   'yanbei_nu': {'name': '孔雀翎武魂',
                                                                 'innate_skill': {'skill_id': 'yanbei',
                                                                                  'name': '孔雀翎魂技'}},
                                                   'yandu_wandao': {'name': '暴雨梨花针武魂',
                                                                    'innate_skill': {'skill_id': 'yandu',
                                                                                     'name': '暴雨梨花针魂技'}},
                                                   'dansha_feiren': {'name': '飞天神爪武魂',
                                                                     'innate_skill': {'skill_id': 'dansha',
                                                                                      'name': '飞天神爪魂技'}},
                                                   'zhuyan_dao': {'name': '龙须针武魂',
                                                                  'innate_skill': {'skill_id': 'zhuyan',
                                                                                   'name': '龙须针魂技'}},
                                                   'chilian_wandao': {'name': '子母追魂胆武魂',
                                                                      'innate_skill': {'skill_id': 'chilian',
                                                                                       'name': '子母追魂胆魂技'}}}},
                       'city_xuantie': {'name': '史莱克学院',
                                        'terrain': '学院',
                                        'roles': ['trade',
                                                  'exploration',
                                                  'city_state',
                                                  'weapon_origin',
                                                  'treasure_map',
                                                  'wormhole_anchor'],
                                        'trade_goods': {'trade_city_xuantie_01': '史莱克校服',
                                                        'trade_city_xuantie_02': '怪物徽章',
                                                        'trade_city_xuantie_03': '拟态训练卡'},
                                        'weapons': {'xuantie_zhongji': {'name': '含沙射影武魂',
                                                                        'innate_skill': {'skill_id': 'bengshan',
                                                                                         'name': '含沙射影魂技'}},
                                                    'zhenyue_fu': {'name': '凤引九雏武魂',
                                                                   'innate_skill': {'skill_id': 'zhenyue',
                                                                                    'name': '凤引九雏魂技'}},
                                                    'heiyao_dunren': {'name': '无声袖箭武魂',
                                                                      'innate_skill': {'skill_id': 'heiyao',
                                                                                       'name': '无声袖箭魂技'}},
                                                    'fanyue_pan': {'name': '泰坦巨猿武魂',
                                                                   'innate_skill': {'skill_id': 'fanyue',
                                                                                    'name': '泰坦巨猿魂技'}},
                                                    'luxin_fu': {'name': '天青牛蟒武魂',
                                                                 'innate_skill': {'skill_id': 'luxin',
                                                                                  'name': '天青牛蟒魂技'}},
                                                    'lingjiao_ji': {'name': '暗魔邪神虎武魂',
                                                                    'innate_skill': {'skill_id': 'lingjiao',
                                                                                     'name': '暗魔邪神虎魂技'}},
                                                    'guming_dunren': {'name': '人面魔蛛武魂',
                                                                      'innate_skill': {'skill_id': 'guming',
                                                                                       'name': '人面魔蛛魂技'}}}},
                       'city_wanyao': {'name': '星斗大森林',
                                       'terrain': '魂兽森林',
                                       'roles': ['trade',
                                                 'exploration',
                                                 'city_state',
                                                 'weapon_origin',
                                                 'treasure_map',
                                                 'wormhole_anchor'],
                                       'trade_goods': {'trade_city_wanyao_01': '星斗兽皮',
                                                       'trade_city_wanyao_02': '魂兽晶核',
                                                       'trade_city_wanyao_03': '森林露营牌'},
                                       'weapons': {'wanyao_tengzhang': {'name': '曼陀罗蛇武魂',
                                                                        'innate_skill': {'skill_id': 'huichun',
                                                                                         'name': '曼陀罗蛇魂技'}},
                                                   'lingfeng_bi': {'name': '邪魔虎鲸武魂',
                                                                   'innate_skill': {'skill_id': 'lingfeng',
                                                                                    'name': '邪魔虎鲸魂技'}},
                                                   'yaowang_fuchen': {'name': '深海魔鲸武魂',
                                                                      'innate_skill': {'skill_id': 'yaowang',
                                                                                       'name': '深海魔鲸魂技'}},
                                                   'fengwang_ling': {'name': '冰碧帝皇蝎武魂',
                                                                     'innate_skill': {'skill_id': 'fengwang',
                                                                                      'name': '冰碧帝皇蝎魂技'}},
                                                   'lingmu_zhang': {'name': '黄金圣龙武魂',
                                                                    'innate_skill': {'skill_id': 'lingmu',
                                                                                     'name': '黄金圣龙魂技'}},
                                                   'luming_qiang': {'name': '白甲地龙武魂',
                                                                    'innate_skill': {'skill_id': 'luming',
                                                                                     'name': '白甲地龙魂技'}},
                                                   'zhupo_zhang': {'name': '鬼藤武魂',
                                                                   'innate_skill': {'skill_id': 'zhupo',
                                                                                    'name': '鬼藤魂技'}}}},
                       'city_yunmeng': {'name': '落日森林',
                                        'terrain': '药毒森林',
                                        'roles': ['trade',
                                                  'exploration',
                                                  'city_state',
                                                  'weapon_origin',
                                                  'treasure_map',
                                                  'wormhole_anchor'],
                                        'trade_goods': {'trade_city_yunmeng_01': '冰火药圃签',
                                                        'trade_city_yunmeng_02': '仙草封盒',
                                                        'trade_city_yunmeng_03': '落日毒雾瓶'},
                                        'weapons': {'duannian_zhang': {'name': '千钧蚁皇武魂',
                                                                       'innate_skill': {'skill_id': 'duannian',
                                                                                        'name': '千钧蚁皇魂技'}},
                                                    'mengwu_ling': {'name': '九宝琉璃塔武魂',
                                                                    'innate_skill': {'skill_id': 'mengwu',
                                                                                     'name': '九宝琉璃塔魂技'}},
                                                    'shuijing_jian': {'name': '白虎烈光波武魂',
                                                                      'innate_skill': {'skill_id': 'shuijing',
                                                                                       'name': '白虎烈光波魂技'}},
                                                    'nimeng_deng': {'name': '凤凰火线武魂',
                                                                    'innate_skill': {'skill_id': 'nimeng',
                                                                                     'name': '凤凰火线魂技'}},
                                                    'jinghu_xijian': {'name': '蓝银囚笼武魂',
                                                                      'innate_skill': {'skill_id': 'jinghu',
                                                                                       'name': '蓝银囚笼魂技'}},
                                                    'heishui_bi': {'name': '昊天护体武魂',
                                                                   'innate_skill': {'skill_id': 'heishui',
                                                                                    'name': '昊天护体魂技'}},
                                                    'duhun_deng': {'name': '鬼影迷踪武魂',
                                                                   'innate_skill': {'skill_id': 'duhun',
                                                                                    'name': '鬼影迷踪魂技'}}}},
                       'city_liusha': {'name': '天斗城',
                                       'terrain': '王城',
                                       'roles': ['trade',
                                                 'exploration',
                                                 'city_state',
                                                 'weapon_origin',
                                                 'treasure_map',
                                                 'wormhole_anchor'],
                                       'trade_goods': {'trade_city_liusha_01': '天斗金券',
                                                       'trade_city_liusha_02': '皇家学院帖',
                                                       'trade_city_liusha_03': '拍卖会号牌'},
                                       'weapons': {'liusha_feiren': {'name': '紫极魔瞳武魂',
                                                                     'innate_skill': {'skill_id': 'shaying',
                                                                                      'name': '紫极魔瞳魂技'}},
                                                   'jueying_feijian': {'name': '玄玉手武魂',
                                                                       'innate_skill': {'skill_id': 'jueying',
                                                                                        'name': '玄玉手魂技'}},
                                                   'duyun_wandao': {'name': '控鹤擒龙武魂',
                                                                    'innate_skill': {'skill_id': 'duyun',
                                                                                     'name': '控鹤擒龙魂技'}},
                                                   'shajin_dao': {'name': '乱披风锤武魂',
                                                                  'innate_skill': {'skill_id': 'shajin',
                                                                                   'name': '乱披风锤魂技'}},
                                                   'yingye_feiren': {'name': '大须弥锤武魂',
                                                                     'innate_skill': {'skill_id': 'yingye',
                                                                                      'name': '大须弥锤魂技'}},
                                                   'langhao_feiren': {'name': '无定风波武魂',
                                                                      'innate_skill': {'skill_id': 'langhao',
                                                                                       'name': '无定风波魂技'}}}},
                       'city_hanshuang': {'name': '武魂城',
                                          'terrain': '圣城',
                                          'roles': ['trade',
                                                    'exploration',
                                                    'city_state',
                                                    'weapon_origin',
                                                    'treasure_map',
                                                    'wormhole_anchor'],
                                          'trade_goods': {'trade_city_hanshuang_01': '武魂殿徽令',
                                                          'trade_city_hanshuang_02': '主教红印',
                                                          'trade_city_hanshuang_03': '魂师通缉榜'},
                                          'weapons': {'xuehe_bi': {'name': '海神之光武魂',
                                                                   'innate_skill': {'skill_id': 'xueying',
                                                                                    'name': '海神之光魂技'}},
                                                      'zhenhun_ling': {'name': '天使圣剑武魂',
                                                                       'innate_skill': {'skill_id': 'liehun',
                                                                                        'name': '天使圣剑魂技'}},
                                                      'yueshi_wandao': {'name': '罗刹魔镰武魂',
                                                                        'innate_skill': {'skill_id': 'yueshi',
                                                                                         'name': '罗刹魔镰魂技'}},
                                                      'hanyan_fuchen': {'name': '杀神领域武魂',
                                                                        'innate_skill': {'skill_id': 'hanyan',
                                                                                         'name': '杀神领域魂技'}},
                                                      'yuehen_bi': {'name': '蓝银领域武魂',
                                                                    'innate_skill': {'skill_id': 'yuehen',
                                                                                     'name': '蓝银领域魂技'}},
                                                      'chenyuan_dao': {'name': '天斗令武魂',
                                                                       'innate_skill': {'skill_id': 'chenyuan',
                                                                                        'name': '天斗令魂技'}}}},
                       'city_leize': {'name': '七宝琉璃宗',
                                      'terrain': '宝塔宗门',
                                      'roles': ['trade',
                                                'exploration',
                                                'city_state',
                                                'weapon_origin',
                                                'treasure_map',
                                                'wormhole_anchor'],
                                      'trade_goods': {'trade_city_leize_01': '七宝琉璃票',
                                                      'trade_city_leize_02': '琉璃塔片',
                                                      'trade_city_leize_03': '宗门账册'},
                                      'weapons': {'pojun_qiang': {'name': '星罗虎符武魂',
                                                                  'innate_skill': {'skill_id': 'pojun',
                                                                                   'name': '星罗虎符魂技'}},
                                                  'leiguang_duanren': {'name': '史莱克战旗武魂',
                                                                       'innate_skill': {'skill_id': 'leiguang',
                                                                                        'name': '史莱克战旗魂技'}},
                                                  'zidian_fu': {'name': '武魂殿圣徽武魂',
                                                                'innate_skill': {'skill_id': 'zidian',
                                                                                 'name': '武魂殿圣徽魂技'}},
                                                  'leihou_dunren': {'name': '七怪徽章武魂',
                                                                    'innate_skill': {'skill_id': 'leihou',
                                                                                     'name': '七怪徽章魂技'}},
                                                  'guigen_dunren': {'name': '唐门令武魂',
                                                                    'innate_skill': {'skill_id': 'guigen',
                                                                                     'name': '唐门令魂技'}},
                                                  'shouhun_ling': {'name': '海神令武魂',
                                                                   'innate_skill': {'skill_id': 'shouhun',
                                                                                    'name': '海神令魂技'}}}},
                       'city_bichao': {'name': '昊天宗',
                                       'terrain': '山门',
                                       'roles': ['trade',
                                                 'exploration',
                                                 'city_state',
                                                 'weapon_origin',
                                                 'treasure_map',
                                                 'wormhole_anchor'],
                                       'trade_goods': {'trade_city_bichao_01': '昊天铁锭',
                                                       'trade_city_bichao_02': '乱披风锤谱',
                                                       'trade_city_bichao_03': '山门云牌'},
                                       'weapons': {'xuangui_dunren': {'name': '银龙鳞武魂',
                                                                      'innate_skill': {'skill_id': 'xuandun',
                                                                                       'name': '银龙鳞魂技'}},
                                                   'duanhai_jian': {'name': '金龙爪武魂',
                                                                    'innate_skill': {'skill_id': 'duanhai',
                                                                                     'name': '金龙爪魂技'}},
                                                   'chaoxi_fuchen': {'name': '魂导炮',
                                                                     'innate_skill': {'skill_id': 'chaoxi',
                                                                                      'name': '魂导炮魂技'}},
                                                   'cangming_ji': {'name': '魂导护盾',
                                                                   'innate_skill': {'skill_id': 'cangming',
                                                                                    'name': '魂导护盾魂技'}},
                                                   'yingyue_pan': {'name': '魂导飞剑',
                                                                   'innate_skill': {'skill_id': 'yingyue',
                                                                                    'name': '魂导飞剑魂技'}},
                                                   'wumu_dunren': {'name': '魂导弩机',
                                                                   'innate_skill': {'skill_id': 'wumu',
                                                                                    'name': '魂导弩机魂技'}}}},
                       'city_xingyun': {'name': '海神岛',
                                        'terrain': '海岛',
                                        'roles': ['trade',
                                                  'exploration',
                                                  'city_state',
                                                  'weapon_origin',
                                                  'treasure_map',
                                                  'wormhole_anchor'],
                                        'trade_goods': {'trade_city_xingyun_01': '海神贝币',
                                                        'trade_city_xingyun_02': '海神试炼签',
                                                        'trade_city_xingyun_03': '紫珍珠航票'},
                                        'weapons': {'zhuixing_nu': {'name': '魂导阵盘',
                                                                    'innate_skill': {'skill_id': 'zhuixing',
                                                                                     'name': '魂导阵盘魂技'}},
                                                    'chuanyun_lingqiang': {'name': '魂导法杖',
                                                                           'innate_skill': {'skill_id': 'chuanyun',
                                                                                            'name': '魂导法杖魂技'}},
                                                    'xingluo_fachen': {'name': '魂导战戟',
                                                                       'innate_skill': {'skill_id': 'xingluo',
                                                                                        'name': '魂导战戟魂技'}},
                                                    'yunxing_pan': {'name': '魂导短刀',
                                                                    'innate_skill': {'skill_id': 'yunxing',
                                                                                     'name': '魂导短刀魂技'}},
                                                    'jinlu_pan': {'name': '魂导灵铃',
                                                                  'innate_skill': {'skill_id': 'jinlu',
                                                                                   'name': '魂导灵铃魂技'}},
                                                    'zhuxie_qiang': {'name': '魂导星盘',
                                                                     'innate_skill': {'skill_id': 'zhuxie',
                                                                                      'name': '魂导星盘魂技'}}}}},
            'realm': {'realm_taixu': {'name': '杀戮之都', 'terrain': '杀戮秘境', 'roles': ['secret_realm', 'dynamic_battle']}},
            'buyers': {'buyer_zhenyaosi': {'name': '武魂殿执法所', 'terrain': '圣殿', 'roles': ['special_buyer', 'war_prep']},
                       'buyer_fumodian': {'name': '邪魂师清剿庭', 'terrain': '审判庭', 'roles': ['special_buyer', 'war_prep']},
                       'buyer_guishi': {'name': '杀戮黑市', 'terrain': '黑市', 'roles': ['special_buyer', 'war_prep']},
                       'buyer_longyuan': {'name': '蓝电龙宗库', 'terrain': '龙宗', 'roles': ['special_buyer', 'war_prep']},
                       'buyer_wanshou': {'name': '星斗兽盟', 'terrain': '兽林', 'roles': ['special_buyer', 'war_prep']},
                       'buyer_pojun': {'name': '唐门军械堂', 'terrain': '军械堂', 'roles': ['special_buyer', 'war_prep']}},
            'recycles': {'recycle_weapon': {'name': '庚辛城铁匠协会', 'terrain': '铁匠城', 'roles': ['recycle']},
                         'recycle_gem': {'name': '七宝鉴宝楼', 'terrain': '宝楼', 'roles': ['recycle']},
                         'recycle_book': {'name': '唐门藏经阁', 'terrain': '藏经阁', 'roles': ['recycle']}}},
 'world_items': {'medicine': {'material': {'world_med_xueqidan_1': '蓝银草叶',
                                           'world_med_xueqidan_2': '八角玄冰草',
                                           'world_med_yinmingcao_1': '烈火杏娇疏',
                                           'world_med_yinmingcao_2': '望穿秋水露',
                                           'world_med_huichunlu_1': '奇茸通天菊',
                                           'world_med_huichunlu_2': '水晶血龙参',
                                           'world_med_ningshenlu_1': '九品紫芝',
                                           'world_med_ningshenlu_2': '相思断肠红瓣'},
                              'catalyst': {'world_med_shenggudan_1': '冰火两仪泉泥',
                                           'world_med_shenggudan_2': '幽香绮罗露',
                                           'world_med_yanghundan_1': '绮罗郁金香粉',
                                           'world_med_yanghundan_2': '鸡冠凤凰葵蕊'},
                              'fuel': {'world_med_xueqidan_3': '凤凰火羽灰',
                                       'world_med_yinmingcao_3': '昊天炉炭',
                                       'world_med_huichunlu_3': '紫极瞳砂',
                                       'world_med_ningshenlu_3': '玄玉手粉',
                                       'world_med_shenggudan_3': '魂环余烬',
                                       'world_med_yanghundan_3': '魂骨温髓'}},
                 'life': {'chengshi': {'world_life_chengshi_1': '魂师口粮',
                                       'world_life_chengshi_2': '史莱克麦饼',
                                       'world_life_chengshi_3': '星斗薯干',
                                       'world_life_chengshi_4': '天斗精米',
                                       'world_life_chengshi_5': '海神岛椰粮'},
                          'yanxian': {'world_life_yanxian_1': '瀚海盐晶',
                                      'world_life_yanxian_2': '星罗腊肉',
                                      'world_life_yanxian_3': '索托烤肠',
                                      'world_life_yanxian_4': '深海鱼干',
                                      'world_life_yanxian_5': '魂兽肉脯'},
                          'shuijing': {'world_life_shuijing_1': '冰火泉滤石',
                                       'world_life_shuijing_2': '蓝银净水草',
                                       'world_life_shuijing_3': '海神岛泉瓶',
                                       'world_life_shuijing_4': '七宝净壶',
                                       'world_life_shuijing_5': '落日避毒炭'},
                          'yibei': {'world_life_yibei_1': '史莱克校服布',
                                    'world_life_yibei_2': '天斗绒毯',
                                    'world_life_yibei_3': '星罗虎纹毡',
                                    'world_life_yibei_4': '海神蓝纱',
                                    'world_life_yibei_5': '武魂殿白袍料'},
                          'ranan': {'world_life_ranan_1': '凤凰暖炉',
                                    'world_life_ranan_2': '魂导长明灯',
                                    'world_life_ranan_3': '驱魂香',
                                    'world_life_ranan_4': '七宝夜珠',
                                    'world_life_ranan_5': '蓝银安神草'}},
                 'build': {'jichu': {'world_build_jichu_1': '庚辛精铁砖',
                                     'world_build_jichu_2': '昊天玄铁梁',
                                     'world_build_jichu_3': '七宝琉璃瓦',
                                     'world_build_jichu_4': '蓝银藤筋',
                                     'world_build_jichu_5': '海神礁石'},
                           'chengfang': {'world_build_chengfang_1': '唐门弩墙',
                                         'world_build_chengfang_2': '魂导护城盾',
                                         'world_build_chengfang_3': '蓝电龙桩',
                                         'world_build_chengfang_4': '昊天闸门',
                                         'world_build_chengfang_5': '七宝警铃'},
                           'shuihuo': {'world_build_shuihuo_1': '冰火泉管',
                                       'world_build_shuihuo_2': '凤凰避火砂',
                                       'world_build_shuihuo_3': '瀚海导潮箍',
                                       'world_build_shuihuo_4': '雷霆引魂桩',
                                       'world_build_shuihuo_5': '落日毒雾闸'},
                           'zhenji': {'world_build_zhenji_1': '魂导阵基',
                                      'world_build_zhenji_2': '七宝聚魂砂',
                                      'world_build_zhenji_3': '武魂殿封印钉',
                                      'world_build_zhenji_4': '唐门暗器槽',
                                      'world_build_zhenji_5': '海神神念石'},
                           'huashi': {'world_build_huashi_1': '琉璃塔檐',
                                      'world_build_huashi_2': '蓝银花窗',
                                      'world_build_huashi_3': '海神纹灯',
                                      'world_build_huashi_4': '天斗金壁',
                                      'world_build_huashi_5': '史莱克怪物匾'}},
                 'relic': {'weiyun': {'world_relic_weiyun_1': '旧魂环碎片',
                                      'world_relic_weiyun_2': '蓝银皇残叶',
                                      'world_relic_weiyun_3': '唐门袖箭簧',
                                      'world_relic_weiyun_4': '武魂殿旧徽',
                                      'world_relic_weiyun_5': '史莱克旧徽',
                                      'world_relic_weiyun_6': '七宝塔角',
                                      'world_relic_weiyun_7': '昊天锤纹片',
                                      'world_relic_weiyun_8': '海神贝冠'},
                           'zhongyun': {'world_relic_zhongyun_1': '八蛛矛残刺',
                                        'world_relic_zhongyun_2': '天使圣羽',
                                        'world_relic_zhongyun_3': '罗刹黑纱',
                                        'world_relic_zhongyun_4': '海神三叉影',
                                        'world_relic_zhongyun_5': '杀神令牌',
                                        'world_relic_zhongyun_6': '冰火泉心石',
                                        'world_relic_zhongyun_7': '龙须针匣',
                                        'world_relic_zhongyun_8': '斗魂冠军章'},
                           'houyun': {'world_relic_houyun_1': '十万年魂环印',
                                      'world_relic_houyun_2': '十万年魂骨匣',
                                      'world_relic_houyun_3': '海神神念珠',
                                      'world_relic_houyun_4': '修罗剑鞘',
                                      'world_relic_houyun_5': '蓝银皇冠',
                                      'world_relic_houyun_6': '天使神辉冠',
                                      'world_relic_houyun_7': '九宝琉璃心',
                                      'world_relic_houyun_8': '昊天宗祖锤印'}},
                 'loot': {'yao': {'loot_yao_1': '魂兽内丹',
                                  'loot_yao_2': '魂兽脊骨',
                                  'loot_yao_3': '魂兽血晶',
                                  'loot_yao_4': '魂兽甲皮',
                                  'loot_yao_5': '魂兽瞳珠',
                                  'loot_yao_6': '魂兽魂晶'},
                          'mo': {'loot_mo_1': '邪魂师魂核',
                                 'loot_mo_2': '邪魔虎角',
                                 'loot_mo_3': '魔鲸血石',
                                 'loot_mo_4': '邪纹皮',
                                 'loot_mo_5': '暗魔爪',
                                 'loot_mo_6': '罗刹灰'},
                          'gui': {'loot_gui_1': '鬼藤阴珠',
                                  'loot_gui_2': '幽冥鬼火',
                                  'loot_gui_3': '残魂旗',
                                  'loot_gui_4': '白骨魂片',
                                  'loot_gui_5': '杀戮纸契',
                                  'loot_gui_6': '怨灵瓶'},
                          'long': {'loot_long_1': '蓝电逆鳞', 'loot_long_2': '龙须针丝', 'loot_long_3': '龙血晶'},
                          'shou': {'loot_shou_1': '泰坦兽筋',
                                   'loot_shou_2': '魔蛛毒牙',
                                   'loot_shou_3': '魂兽腿骨',
                                   'loot_shou_4': '灵猫纹皮',
                                   'loot_shou_5': '天青牛角',
                                   'loot_shou_6': '魂兽心核'},
                          'bing': {'loot_bing_1': '唐门军魂印',
                                   'loot_bing_2': '破甲弩片',
                                   'loot_bing_3': '暗器残符',
                                   'loot_bing_4': '战队血旗',
                                   'loot_bing_5': '庚辛锈铁',
                                   'loot_bing_6': '断裂魂刃'}}},
 'ring': {'recovery': {'fudai': '魂师福袋',
                       'xueqidan': '蓝银血契丹',
                       'yinmingcao': '鬼藤阴冥草',
                       'huichunlu': '九心回春露',
                       'ningshenlu': '紫极凝神露',
                       'shenggudan': '魂骨生骨丹',
                       'yanghundan': '海棠养魂丹'},
          'gems': {'huxinyu': '七宝护心玉',
                   'xuangui shi': '玄武龟甲石',
                   'shanbi fozhu': '鬼影佛珠',
                   'mingxin fozhu': '紫极明心珠',
                   'huichun feicui': '九心翡翠',
                   'qingxin manao': '蓝银玛瑙',
                   'qingshen shuijing': '柔骨水晶',
                   'jucai zijing': '七宝紫晶',
                   'kangbao fuwen': '魂导抗暴纹'},
          'special': {'kaikongqi': '魂导开槽器', 'xisuiye': '武魂洗髓液', 'cuifengdan': '魂骨淬锋丹', 'liuguang_qian': '魂光签'}},
 'weapons': {'skill_books': {'fengren_shu': '蓝银魂技书',
                             'extreme_fengren_shu': '极·蓝银魂技书',
                             'shaying_shu': '昊天魂技书',
                             'extreme_shaying_shu': '极·昊天魂技书',
                             'liuguang_shu': '柔骨魂技书',
                             'extreme_liuguang_shu': '极·柔骨魂技书',
                             'zhuixing_shu': '白虎魂技书',
                             'extreme_zhuixing_shu': '极·白虎魂技书',
                             'poxie_shu': '幽冥魂技书',
                             'extreme_poxie_shu': '极·幽冥魂技书',
                             'bengshan_shu': '香肠魂技书',
                             'extreme_bengshan_shu': '极·香肠魂技书',
                             'chuanyun_shu': '七宝魂技书',
                             'extreme_chuanyun_shu': '极·七宝魂技书',
                             'zhenyue_shu': '凤凰魂技书',
                             'extreme_zhenyue_shu': '极·凤凰魂技书',
                             'zhuoxin_shu': '蓝电魂技书',
                             'extreme_zhuoxin_shu': '极·蓝电魂技书',
                             'xueyu_shu': '碧磷魂技书',
                             'extreme_xueyu_shu': '极·碧磷魂技书',
                             'duyun_shu': '海棠魂技书',
                             'extreme_duyun_shu': '极·海棠魂技书',
                             'canyan_shu': '天使魂技书',
                             'extreme_canyan_shu': '极·天使魂技书',
                             'duannian_shu': '海神魂技书',
                             'extreme_duannian_shu': '极·海神魂技书',
                             'zhenhun_shu': '修罗魂技书',
                             'extreme_zhenhun_shu': '极·修罗魂技书',
                             'tianji_shu': '八蛛魂技书',
                             'extreme_tianji_shu': '极·八蛛魂技书',
                             'mengwu_shu': '诸葛魂技书',
                             'extreme_mengwu_shu': '极·诸葛魂技书',
                             'huichun_shu': '孔雀魂技书',
                             'extreme_huichun_shu': '极·孔雀魂技书',
                             'xuandun_shu': '梨花魂技书',
                             'extreme_xuandun_shu': '极·梨花魂技书',
                             'xueqi_shu': '飞爪魂技书',
                             'extreme_xueqi_shu': '极·飞爪魂技书',
                             'lingmu_shu': '龙须魂技书',
                             'extreme_lingmu_shu': '极·龙须魂技书',
                             'fanzhen_shu': '追魂魂技书',
                             'extreme_fanzhen_shu': '极·追魂魂技书',
                             'guiren_shu': '含沙魂技书',
                             'extreme_guiren_shu': '极·含沙魂技书',
                             'jieshi_shu': '凤引魂技书',
                             'extreme_jieshi_shu': '极·凤引魂技书',
                             'xuanyao_shu': '袖箭魂技书',
                             'extreme_xuanyao_shu': '极·袖箭魂技书',
                             'wuxiang_shu': '泰坦魂技书',
                             'extreme_wuxiang_shu': '极·泰坦魂技书',
                             'duanhai_shu': '天青魂技书',
                             'extreme_duanhai_shu': '极·天青魂技书',
                             'jueying_shu': '邪虎魂技书',
                             'extreme_jueying_shu': '极·邪虎魂技书',
                             'pojun_shu': '魔蛛魂技书',
                             'extreme_pojun_shu': '极·魔蛛魂技书',
                             'xingluo_shu': '曼陀魂技书',
                             'extreme_xingluo_shu': '极·曼陀魂技书',
                             'qiankun_shu': '虎鲸魂技书',
                             'extreme_qiankun_shu': '极·虎鲸魂技书',
                             'pozhen_shu': '魔鲸魂技书',
                             'extreme_pozhen_shu': '极·魔鲸魂技书',
                             'yujing_shu': '冰碧魂技书',
                             'extreme_yujing_shu': '极·冰碧魂技书',
                             'yueshi_shu': '黄金圣龙魂技书',
                             'extreme_yueshi_shu': '极·黄金圣龙魂技书',
                             'jinghu_shu': '白甲地龙魂技书',
                             'extreme_jinghu_shu': '极·白甲地龙魂技书',
                             'yingye_shu': '鬼藤魂技书',
                             'extreme_yingye_shu': '极·鬼藤魂技书',
                             'qingxin_shu': '千钧蚁魂技书',
                             'extreme_qingxin_shu': '极·千钧蚁魂技书'},
             'types': {'axe': '器武魂斧',
                       'balanced': '均衡武魂',
                       'bell': '铃类器武魂',
                       'blade': '飞刃暗器',
                       'crossbow': '神弩暗器',
                       'dagger': '匕类武魂',
                       'disc': '阵盘魂导器',
                       'halberd': '战戟武魂',
                       'saber': '刀类武魂',
                       'shield_blade': '盾刃魂导器',
                       'spear': '枪类武魂',
                       'staff': '杖类器武魂',
                       'sword': '剑类武魂',
                       'whisk': '拂尘器武魂'}},
 'actors': {'monsters': {'qinglang': '曼陀罗蛇',
                         'huyao': '人面魔蛛',
                         'shanzhu': '疾风魔狼',
                         'baigui': '白骨邪魂',
                         'shayan': '沙地魔蝎',
                         'mopi_jiang': '邪魔虎影',
                         'xuanling': '玄铁魂傀',
                         'guijiang': '幽冥鬼虎',
                         'hanpo': '冰碧蝎影',
                         'tiejia_bing': '铁甲魂兵',
                         'leishou': '雷霆魔豹',
                         'yaotong_niao': '妖眼魔鸦',
                         'jiaolong': '天青牛蟒影',
                         'longxu_ying': '蓝电龙影',
                         'mohun': '邪魂将',
                         'moyan_shi': '凤凰魔焰使',
                         'pojun': '破军魂将',
                         'duanren_jiang': '断刃斗魂兵'},
            "physiques": {
                "fanti": {
                    "name": "先天零魂力",
                    "grade": "未觉醒",
                    "kind": "均衡",
                    "desc": "先天零魂力以均衡路线觉醒，魂力表现对应原体质：平平无奇，却也最稳，所有玩家默认从这里开始。",
                },
                "qingfeng_lingti": {
                    "name": "风鹰武魂",
                    "grade": "黄环",
                    "kind": "敏攻",
                    "desc": "风鹰武魂以敏攻路线觉醒，魂力表现对应原体质：气息轻灵，稍微更容易避开伤害。",
                },
                "houde_lingti": {
                    "name": "大地熊武魂",
                    "grade": "黄环",
                    "kind": "强攻",
                    "desc": "大地熊武魂以强攻路线觉醒，魂力表现对应原体质：根基厚实，早期防御更稳。",
                },
                "lingquan_ti": {
                    "name": "九心海棠体",
                    "grade": "黄环",
                    "kind": "治疗",
                    "desc": "九心海棠体以治疗路线觉醒，魂力表现对应原体质：体内如有活泉，休息恢复更好。",
                },
                "tiegu_ti": {
                    "name": "玄龟甲体",
                    "grade": "黄环",
                    "kind": "防御",
                    "desc": "玄龟甲体以防御路线觉醒，魂力表现对应原体质：骨骼坚韧，承伤更稳。",
                },
                "mingxin_ti": {
                    "name": "紫极明心体",
                    "grade": "黄环",
                    "kind": "精神",
                    "desc": "紫极明心体以精神路线觉醒，魂力表现对应原体质：心神清明，精神上限略高。",
                },
                "qianye_lingti": {
                    "name": "蓝银草体",
                    "grade": "黄环",
                    "kind": "植物",
                    "desc": "蓝银草体以植物路线觉醒，魂力表现对应原体质：生机细密，血气和恢复都有一点优势。",
                },
                "qingmu_xuanti": {
                    "name": "蓝银皇血脉",
                    "grade": "紫环",
                    "kind": "植物",
                    "desc": "蓝银皇血脉以植物路线觉醒，魂力表现对应原体质：偏生机恢复，跑商手续费略吃亏。",
                },
                "xuanbing_linggu": {
                    "name": "冰碧灵骨",
                    "grade": "紫环",
                    "kind": "冰魂",
                    "desc": "冰碧灵骨以冰魂路线觉醒，魂力表现对应原体质：防御冷硬，恢复稍慢。",
                },
                "chixia_lingti": {
                    "name": "凤凰火体",
                    "grade": "紫环",
                    "kind": "火魂",
                    "desc": "凤凰火体以火魂路线觉醒，魂力表现对应原体质：血气旺盛，精神上限略低。",
                },
                "leiwenzhanti": {
                    "name": "蓝电战体",
                    "grade": "紫环",
                    "kind": "雷魂",
                    "desc": "蓝电战体以雷魂路线觉醒，魂力表现对应原体质：身法迅疾，生活经营不太细致。",
                },
                "yuyue_ti": {
                    "name": "月兔灵体",
                    "grade": "紫环",
                    "kind": "月光",
                    "desc": "月兔灵体以月光路线觉醒，魂力表现对应原体质：精神与恢复突出，血气略薄。",
                },
                "jianxin_xuangu": {
                    "name": "七杀剑心",
                    "grade": "紫环",
                    "kind": "器武魂",
                    "desc": "七杀剑心以器武魂路线觉醒，魂力表现对应原体质：适合冒险寻机，身板略薄。",
                },
                "longxiang_baoti": {
                    "name": "白虎宝体",
                    "grade": "黑环",
                    "kind": "强攻",
                    "desc": "白虎宝体以强攻路线觉醒，魂力表现对应原体质：血厚防稳，跑商不灵活。",
                },
                "xinghe_lingti": {
                    "name": "星冠灵体",
                    "grade": "黑环",
                    "kind": "星罗",
                    "desc": "星冠灵体以星罗路线觉醒，魂力表现对应原体质：擅长探险寻宝，防御略低。",
                },
                "taiyin_yuti": {
                    "name": "海棠玉体",
                    "grade": "黑环",
                    "kind": "月光",
                    "desc": "海棠玉体以月光路线觉醒，魂力表现对应原体质：恢复和精神很强，血气偏薄。",
                },
                "taiyang_yanti": {
                    "name": "太阳天使体",
                    "grade": "黑环",
                    "kind": "火魂",
                    "desc": "太阳天使体以火魂路线觉醒，魂力表现对应原体质：血气极盛，恢复和跑商略差。",
                },
                "canghai_daoti": {
                    "name": "瀚海道体",
                    "grade": "黑环",
                    "kind": "海魂",
                    "desc": "瀚海道体以海魂路线觉醒，魂力表现对应原体质：精神绵长、恢复平顺，防御偏弱。",
                },
                "wuyue_baoti": {
                    "name": "玄武宝体",
                    "grade": "黑环",
                    "kind": "大地",
                    "desc": "玄武宝体以大地路线觉醒，魂力表现对应原体质：防御厚重，精神和探险灵活性较差。",
                },
                "hunyuan_daoti": {
                    "name": "昊天镇岳体",
                    "grade": "红环",
                    "kind": "大地",
                    "desc": "昊天镇岳体以大地路线觉醒，魂力表现对应原体质：极端守御体质，精神与跑商是短板。",
                },
                "wugou_xianji": {
                    "name": "九宝琉璃体",
                    "grade": "红环",
                    "kind": "净化",
                    "desc": "九宝琉璃体以净化路线觉醒，魂力表现对应原体质：恢复与精神突出，正面承伤略弱。",
                },
                "wanxiang_lingtai": {
                    "name": "鬼影游身体",
                    "grade": "红环",
                    "kind": "敏攻",
                    "desc": "鬼影游身体以敏攻路线觉醒，魂力表现对应原体质：闪避和探险极强，血防明显偏薄。",
                },
                "zifu_tianti": {
                    "name": "精神海神体",
                    "grade": "红环",
                    "kind": "精神",
                    "desc": "精神海神体以精神路线觉醒，魂力表现对应原体质：精神海宽广，血气不是优势。",
                },
                "qianqiu_jianmai": {
                    "name": "千秋剑脉",
                    "grade": "红环",
                    "kind": "器武魂",
                    "desc": "千秋剑脉以器武魂路线觉醒，魂力表现对应原体质：适合险地寻剑，恢复不算出色。",
                },
                "shenxiao_leiti": {
                    "name": "雷霆龙体",
                    "grade": "红环",
                    "kind": "雷魂",
                    "desc": "雷霆龙体以雷魂路线觉醒，魂力表现对应原体质：迅烈难伤，恢复和跑商都粗糙。",
                },
                "xiantian_daotai": {
                    "name": "先天药魂",
                    "grade": "神环",
                    "kind": "治疗",
                    "desc": "先天药魂以治疗路线觉醒，魂力表现对应原体质：恢复近乎夸张，但肉身承压偏弱。",
                },
                "canglong_shengti": {
                    "name": "蓝银圣体",
                    "grade": "神环",
                    "kind": "龙族",
                    "desc": "蓝银圣体以龙族路线觉醒，魂力表现对应原体质：血气如海，精神和经营能力是短板。",
                },
                "jiuyao_shengti": {
                    "name": "星斗命体",
                    "grade": "神环",
                    "kind": "星罗",
                    "desc": "星斗命体以星罗路线觉醒，魂力表现对应原体质：天生会找机会，适合探险和跑商，血防较薄。",
                },
                "bumie_jinshen": {
                    "name": "昊天金身",
                    "grade": "神环",
                    "kind": "不灭",
                    "desc": "昊天金身以不灭路线觉醒，魂力表现对应原体质：最硬的防御路线，精神、探险和跑商都笨重。",
                },
                "taixu_xianmai": {
                    "name": "海神仙脉",
                    "grade": "神环",
                    "kind": "空间",
                    "desc": "海神仙脉以空间路线觉醒，魂力表现对应原体质：飘忽难捉，探险极强，但正面血防很低。",
                },
                "hongmeng_xuanti": {
                    "name": "修罗玄体",
                    "grade": "神环",
                    "kind": "空间",
                    "desc": "修罗玄体以空间路线觉醒，魂力表现对应原体质：精神深不可测，却不适合硬扛和经营。",
                },
            },
            'enemy_kinds': {'ancient_guard': '武魂古卫',
                            'beast': '魂兽',
                            'default': '凶煞魂影',
                            'demon': '邪魂师',
                            'demon_general': '邪魂将',
                            'dragon': '龙系魂兽',
                            'dragon_shadow': '龙影',
                            'ghost': '幽冥鬼虎',
                            'puppet': '魂导傀儡',
                            'soldier': '斗魂兵',
                            'wandering_soul': '游魂',
                            'yao': '妖系魂兽',
                            'yaojun': '妖君'},
            'enemy_skills': {'enemy_skill_yao_bite': '魂兽撕咬',
                             'enemy_skill_yaojun_shadow': '妖影裂魂',
                             'enemy_skill_beast_charge': '魂兽冲撞',
                             'enemy_skill_dragon_breath': '龙息压顶',
                             'enemy_skill_dragon_shadow_breath': '龙影吐息',
                             'enemy_skill_ghost_bite': '幽冥噬念',
                             'enemy_skill_wandering_soul_bind': '游魂缠身',
                             'enemy_skill_demon_flame': '邪火灼心',
                             'enemy_skill_demon_general_break': '邪魂破阵',
                             'enemy_skill_soldier_armor_break': '斗魂破甲',
                             'enemy_skill_ancient_guard_suppress': '武魂殿镇压',
                             'enemy_skill_puppet_crush': '魂傀重压',
                             'enemy_skill_default': '魂力一击'}},
 'wormhole': {'bosses': {'worm_boss_01': '异界魂兽·千刃界游王',
                         'worm_boss_02': '异界魂兽·陨炉泰坦',
                         'worm_boss_03': '异界魂兽·赤瘟炼狱君',
                         'worm_boss_04': '异界魂兽·缄魂巫皇',
                         'worm_boss_05': '异界魂兽·苍根不死王',
                         'worm_boss_06': '异界魂兽·回盾镜魔',
                         'worm_boss_07': '异界魂兽·断星斩王',
                         'worm_boss_08': '异界魂兽·星环仲裁者'},
              'flows': {'worm_flow_swift': '敏攻连击',
                        'worm_flow_heavy': '强攻破防',
                        'worm_flow_dot': '邪火持续',
                        'worm_flow_control': '控制压制',
                        'worm_flow_survival': '辅助续航',
                        'worm_flow_counter': '防御反击',
                        'worm_flow_execute': '强攻斩杀',
                        'worm_flow_leader': '七怪协作'},
              'war_prep_bosses': {'war_boss_zhenyaosi_01': '百臂魂兽王',
                                  'war_boss_zhenyaosi_02': '裂巢魔蛛后',
                                  'war_boss_zhenyaosi_03': '万爪潮主',
                                  'war_boss_fumodian_01': '黑铠邪魂魔',
                                  'war_boss_fumodian_02': '焚契邪火侯',
                                  'war_boss_fumodian_03': '坠岳魔君',
                                  'war_boss_guishi_01': '无灯幽冥主',
                                  'war_boss_guishi_02': '缚魂夜巫',
                                  'war_boss_guishi_03': '杀戮鬼王',
                                  'war_boss_longyuan_01': '逆鳞龙君',
                                  'war_boss_longyuan_02': '潮骸古蛟',
                                  'war_boss_longyuan_03': '星渊断角龙',
                                  'war_boss_wanshou_01': '荒骨兽神',
                                  'war_boss_wanshou_02': '苍鬃不死兽',
                                  'war_boss_wanshou_03': '万蹄裂阵王',
                                  'war_boss_pojun_01': '星甲破阵帅',
                                  'war_boss_pojun_02': '断旗兵主',
                                  'war_boss_pojun_03': '铁潮军魂王'},
              'war_prep_affixes': {'war_prep_affix_exposed_nest': '魂兽巢已露',
                                   'war_prep_affix_half_open_gate': '杀戮门半开',
                                   'war_prep_affix_war_marks': '斗魂战痕',
                                   'war_prep_affix_warm_embers': '余焰未冷',
                                   'war_prep_affix_gathering_enemies': '群兽聚形',
                                   'war_prep_affix_unstable_rift': '裂隙不稳'}},
 'secret_realm': {'environments': {'secret_env_youming_wind': {'name': '幽冥鬼风', 'desc': '阴风压魂，怪物精神压迫更重。'},
                                   'secret_env_mirror_sky': {'name': '镜魂天幕', 'desc': '镜影错乱，遭遇强度起伏更大。'},
                                   'secret_env_dragon_bone_dust': {'name': '龙骨魂尘', 'desc': '龙骨尘暴翻涌，怪物血防更厚。'},
                                   'secret_env_star_fire_rain': {'name': '星斗火雨', 'desc': '星火落如雨，怪物攻势更烈。'},
                                   'secret_env_returning_tide': {'name': '瀚海归潮', 'desc': '归墟潮汐反复，战斗更拖长。'}}},
 'system': {'quality': {'quality_common': '白环', 'quality_good': '黄环', 'quality_rare': '黑环', 'quality_epic': '红环'},
            'currency': {'raw_stones': '金魂币'},
            'levels': {'1': '魂士·武魂觉醒',
                       '2': '魂士·先天魂力',
                       '3': '魂士·冥想入门',
                       '4': '魂士·本源凝芽',
                       '5': '魂士·魂力成溪',
                       '6': '魂士·猎环试炼',
                       '7': '魂士·魂环初鸣',
                       '8': '魂士·第一魂技',
                       '9': '魂士·斗魂启蒙',
                       '10': '魂士·一环在望',
                       '11': '魂师·一环入身',
                       '12': '魂师·魂技熟练',
                       '13': '魂师·武魂契合',
                       '14': '魂师·身法入魂',
                       '15': '魂师·魂力成流',
                       '16': '魂师·战斗节奏',
                       '17': '魂师·魂环共鸣',
                       '18': '魂师·小队配合',
                       '19': '魂师·猎环筹备',
                       '20': '魂师·二环在望',
                       '21': '大魂师·双环初成',
                       '22': '大魂师·魂力成河',
                       '23': '大魂师·武魂显相',
                       '24': '大魂师·双技连携',
                       '25': '大魂师·斗魂连胜',
                       '26': '大魂师·魂环稳固',
                       '27': '大魂师·战魂凝魄',
                       '28': '大魂师·压场成势',
                       '29': '大魂师·魂力破壁',
                       '30': '大魂师·三环在望',
                       '31': '魂尊·三环定势',
                       '32': '魂尊·控场初成',
                       '33': '魂尊·魂技成阵',
                       '34': '魂尊·战意入骨',
                       '35': '魂尊·武魂升华',
                       '36': '魂尊·斗魂扬名',
                       '37': '魂尊·环技相生',
                       '38': '魂尊·魂力如潮',
                       '39': '魂尊·尊威初露',
                       '40': '魂尊·四环在望',
                       '41': '魂宗·四环归位',
                       '42': '魂宗·宗意凝成',
                       '43': '魂宗·魂力厚积',
                       '44': '魂宗·队阵核心',
                       '45': '魂宗·武魂真影',
                       '46': '魂宗·斗魂压城',
                       '47': '魂宗·环域初开',
                       '48': '魂宗·宗威成势',
                       '49': '魂宗·万众侧目',
                       '50': '魂宗·五环在望',
                       '51': '魂王·五环加身',
                       '52': '魂王·王意初显',
                       '53': '魂王·魂力成海',
                       '54': '魂王·武魂威压',
                       '55': '魂王·魂技统御',
                       '56': '魂王·战场主宰',
                       '57': '魂王·魂环生辉',
                       '58': '魂王·王威镇场',
                       '59': '魂王·魂海翻涌',
                       '60': '魂王·六环在望',
                       '61': '魂帝·六环归心',
                       '62': '魂帝·帝意入魂',
                       '63': '魂帝·魂力如渊',
                       '64': '魂帝·武魂压阵',
                       '65': '魂帝·魂技改局',
                       '66': '魂帝·战意成域',
                       '67': '魂帝·魂环化势',
                       '68': '魂帝·斗魂称雄',
                       '69': '魂帝·领域微明',
                       '70': '魂帝·七环在望',
                       '71': '魂圣·武魂真身',
                       '72': '魂圣·真身稳固',
                       '73': '魂圣·真身临阵',
                       '74': '魂圣·武魂化身',
                       '75': '魂圣·圣威镇魂',
                       '76': '魂圣·领域开门',
                       '77': '魂圣·魂力贯天',
                       '78': '魂圣·真身大成',
                       '79': '魂圣·圣意圆满',
                       '80': '魂圣·八环在望',
                       '81': '魂斗罗·八环归位',
                       '82': '魂斗罗·魂域初成',
                       '83': '魂斗罗·魂域稳固',
                       '84': '魂斗罗·武魂压世',
                       '85': '魂斗罗·魂技化界',
                       '86': '魂斗罗·斗罗威仪',
                       '87': '魂斗罗·魂域大成',
                       '88': '魂斗罗·九环在望',
                       '89': '封号斗罗·封号凝名',
                       '90': '封号斗罗·九环加身',
                       '91': '封号斗罗·领域成界',
                       '92': '封号斗罗·封号传世',
                       '93': '超级斗罗·魂力破限',
                       '94': '超级斗罗·领域升华',
                       '95': '超级斗罗·神念初照',
                       '96': '巅峰斗罗·半神之门',
                       '97': '巅峰斗罗·法则回响',
                       '98': '极限斗罗·神祇试炼',
                       '99': '极限斗罗·神位照临',
                       '100': '神祇传承·新神初成'}}}
